// badgeart.js — real per-badge art for the Trainer Card badge case.
//
// Sprites live at fx/badges/<region>_<id>.png (16x16, transparent background),
// generated by tools/gen_badge_art.py from the vendored decomp trainer-card
// badge sheets (pokefirered / pokeemerald / pokecrystal). The decomps store
// card badges as a grayscale ramp colorized by ONE runtime palette shared by
// every badge; the generator keeps the authentic pixels and applies a
// per-badge palette instead, so each badge reads with its iconic color.
// JOHKANTO shares KANTO's art — they are the same eight badges.
//
// badgeSprite(region, id) -> HTMLImageElement | null (kicks off the load on a
// miss; callers fall back to the old pip while it arrives). badgeGhost() is
// the darkened silhouette for unearned slots — shape visible, color withheld.
import { getImage } from './engine.js';

const ART_REGION = { KANTO: 'kanto', JOHTO: 'johto', HOENN: 'hoenn', JOHKANTO: 'kanto' };
const imgs = new Map();   // key -> HTMLImageElement | null (null while loading)
const ghosts = new Map(); // key -> canvas

function artKey(region, id) {
	return (ART_REGION[region] || 'kanto') + '_' + id;
}

export function badgeSprite(region, id) {
	const key = artKey(region, id);
	if (!imgs.has(key)) {
		imgs.set(key, null);
		getImage(`fx/badges/${key}.png`).then(img => imgs.set(key, img)).catch(() => {});
	}
	return imgs.get(key);
}

export function badgeGhost(region, id) {
	const img = badgeSprite(region, id);
	if (!img) return null;
	const key = artKey(region, id);
	let g = ghosts.get(key);
	if (!g) {
		g = document.createElement('canvas');
		g.width = img.width; g.height = img.height;
		const c = g.getContext('2d');
		c.drawImage(img, 0, 0);
		c.globalCompositeOperation = 'source-atop'; // keep the badge's alpha, darken its body
		c.fillStyle = 'rgba(12,20,36,0.85)';
		c.fillRect(0, 0, g.width, g.height);
		ghosts.set(key, g);
	}
	return g;
}
