// GENERATED by tools/gen_crystal_trainer_headers.mjs from pokecrystal maps/*.asm.
// Crystal script labels that are TRAINER HEADERS (seen text -> battle -> beaten
// text -> beat event). A loaded script under one of these labels is the
// after-battle CONTINUATION (the header's .Script), never the first battle.
// label -> { beat: EVENT_BEAT_*, seen: <SeenText label>, beaten: <BeatenText label> }
export const CRYSTAL_TRAINER_HEADERS = {
	"TrainerTwinsAmyandmay1": {
		"beat": "EVENT_BEAT_TWINS_AMY_AND_MAY",
		"seen": "TwinsAmyandmay1SeenText",
		"beaten": "TwinsAmyandmay1BeatenText"
	},
	"TrainerTwinsAmyandmay2": {
		"beat": "EVENT_BEAT_TWINS_AMY_AND_MAY",
		"seen": "TwinsAmyandmay2SeenText",
		"beaten": "TwinsAmyandmay2BeatenText"
	},
	"TrainerBugCatcherBenny": {
		"beat": "EVENT_BEAT_BUG_CATCHER_BENNY",
		"seen": "BugCatcherBennySeenText",
		"beaten": "BugCatcherBennyBeatenText"
	},
	"TrainerBugCatcherAl": {
		"beat": "EVENT_BEAT_BUG_CATCHER_AL",
		"seen": "BugCatcherAlSeenText",
		"beaten": "BugCatcherAlBeatenText"
	},
	"TrainerBugCatcherJosh": {
		"beat": "EVENT_BEAT_BUG_CATCHER_JOSH",
		"seen": "BugCatcherJoshSeenText",
		"beaten": "BugCatcherJoshBeatenText"
	},
	"TrainerCooltrainermPaul": {
		"beat": "EVENT_BEAT_COOLTRAINERM_PAUL",
		"seen": "CooltrainermPaulSeenText",
		"beaten": "CooltrainermPaulBeatenText"
	},
	"TrainerCooltrainermMike": {
		"beat": "EVENT_BEAT_COOLTRAINERM_MIKE",
		"seen": "CooltrainermMikeSeenText",
		"beaten": "CooltrainermMikeBeatenText"
	},
	"TrainerCooltrainerfLola": {
		"beat": "EVENT_BEAT_COOLTRAINERF_LOLA",
		"seen": "CooltrainerfLolaSeenText",
		"beaten": "CooltrainerfLolaBeatenText"
	},
	"TrainerCooltrainermCody": {
		"beat": "EVENT_BEAT_COOLTRAINERM_CODY",
		"seen": "CooltrainermCodySeenText",
		"beaten": "CooltrainermCodyBeatenText"
	},
	"TrainerCooltrainerfFran": {
		"beat": "EVENT_BEAT_COOLTRAINERF_FRAN",
		"seen": "CooltrainerfFranSeenText",
		"beaten": "CooltrainerfFranBeatenText"
	},
	"TrainerLassMichelle": {
		"beat": "EVENT_BEAT_LASS_MICHELLE",
		"seen": "LassMichelleSeenText",
		"beaten": "LassMichelleBeatenText"
	},
	"TrainerPicnickerTanya": {
		"beat": "EVENT_BEAT_PICNICKER_TANYA",
		"seen": "PicnickerTanyaSeenText",
		"beaten": "PicnickerTanyaBeatenText"
	},
	"TrainerBeautyJulia": {
		"beat": "EVENT_BEAT_BEAUTY_JULIA",
		"seen": "BeautyJuliaSeenText",
		"beaten": "BeautyJuliaBeatenText"
	},
	"TrainerTwinsJoAndZoe1": {
		"beat": "EVENT_BEAT_TWINS_JO_AND_ZOE",
		"seen": "TwinsJoAndZoe1SeenText",
		"beaten": "TwinsJoAndZoe1BeatenText"
	},
	"TrainerTwinsJoAndZoe2": {
		"beat": "EVENT_BEAT_TWINS_JO_AND_ZOE",
		"seen": "TwinsJoAndZoe2SeenText",
		"beaten": "TwinsJoAndZoe2BeatenText"
	},
	"TrainerSwimmerfDiana": {
		"beat": "EVENT_BEAT_SWIMMERF_DIANA",
		"seen": "SwimmerfDianaSeenText",
		"beaten": "SwimmerfDianaBeatenText"
	},
	"TrainerSwimmerfBriana": {
		"beat": "EVENT_BEAT_SWIMMERF_BRIANA",
		"seen": "SwimmerfBrianaSeenText",
		"beaten": "SwimmerfBrianaBeatenText"
	},
	"TrainerSwimmermParker": {
		"beat": "EVENT_BEAT_SWIMMERM_PARKER",
		"seen": "SwimmermParkerSeenText",
		"beaten": "SwimmermParkerBeatenText"
	},
	"TrainerBlackbeltYoshi": {
		"beat": "EVENT_BEAT_BLACKBELT_YOSHI",
		"seen": "BlackbeltYoshiSeenText",
		"beaten": "BlackbeltYoshiBeatenText"
	},
	"TrainerBlackbeltLao": {
		"beat": "EVENT_BEAT_BLACKBELT_LAO",
		"seen": "BlackbeltLaoSeenText",
		"beaten": "BlackbeltLaoBeatenText"
	},
	"TrainerBlackbeltNob": {
		"beat": "EVENT_BEAT_BLACKBELT_NOB",
		"seen": "BlackbeltNobSeenText",
		"beaten": "BlackbeltNobBeatenText"
	},
	"TrainerBlackbeltLung": {
		"beat": "EVENT_BEAT_BLACKBELT_LUNG",
		"seen": "BlackbeltLungSeenText",
		"beaten": "BlackbeltLungBeatenText"
	},
	"TrainerKimonoGirlNaoko": {
		"beat": "EVENT_BEAT_KIMONO_GIRL_NAOKO",
		"seen": "KimonoGirlNaokoSeenText",
		"beaten": "KimonoGirlNaokoBeatenText"
	},
	"TrainerKimonoGirlSayo": {
		"beat": "EVENT_BEAT_KIMONO_GIRL_SAYO",
		"seen": "KimonoGirlSayoSeenText",
		"beaten": "KimonoGirlSayoBeatenText"
	},
	"TrainerKimonoGirlZuki": {
		"beat": "EVENT_BEAT_KIMONO_GIRL_ZUKI",
		"seen": "KimonoGirlZukiSeenText",
		"beaten": "KimonoGirlZukiBeatenText"
	},
	"TrainerKimonoGirlKuni": {
		"beat": "EVENT_BEAT_KIMONO_GIRL_KUNI",
		"seen": "KimonoGirlKuniSeenText",
		"beaten": "KimonoGirlKuniBeatenText"
	},
	"TrainerKimonoGirlMiki": {
		"beat": "EVENT_BEAT_KIMONO_GIRL_MIKI",
		"seen": "KimonoGirlMikiSeenText",
		"beaten": "KimonoGirlMikiBeatenText"
	},
	"TrainerCooltrainermDarin": {
		"beat": "EVENT_BEAT_COOLTRAINERM_DARIN",
		"seen": "CooltrainermDarinSeenText",
		"beaten": "CooltrainermDarinBeatenText"
	},
	"TrainerCooltrainerfCara": {
		"beat": "EVENT_BEAT_COOLTRAINERF_CARA",
		"seen": "CooltrainerfCaraSeenText",
		"beaten": "CooltrainerfCaraBeatenText"
	},
	"TrainerTwinsLeaandpia1": {
		"beat": "EVENT_BEAT_TWINS_LEA_AND_PIA",
		"seen": "TwinsLeaandpia1SeenText",
		"beaten": "TwinsLeaandpia1BeatenText"
	},
	"TrainerTwinsLeaandpia2": {
		"beat": "EVENT_BEAT_TWINS_LEA_AND_PIA",
		"seen": "TwinsLeaandpia2SeenText",
		"beaten": "TwinsLeaandpia2BeatenText"
	},
	"TrainerSageJeffrey": {
		"beat": "EVENT_BEAT_SAGE_JEFFREY",
		"seen": "SageJeffreySeenText",
		"beaten": "SageJeffreyBeatenText"
	},
	"TrainerSagePing": {
		"beat": "EVENT_BEAT_SAGE_PING",
		"seen": "SagePingSeenText",
		"beaten": "SagePingBeatenText"
	},
	"TrainerMediumMartha": {
		"beat": "EVENT_BEAT_MEDIUM_MARTHA",
		"seen": "MediumMarthaSeenText",
		"beaten": "MediumMarthaBeatenText"
	},
	"TrainerMediumGrace": {
		"beat": "EVENT_BEAT_MEDIUM_GRACE",
		"seen": "MediumGraceSeenText",
		"beaten": "MediumGraceBeatenText"
	},
	"TrainerSailorJeff": {
		"beat": "EVENT_BEAT_SAILOR_JEFF",
		"seen": "SailorJeffSeenText",
		"beaten": "SailorJeffBeatenText"
	},
	"TrainerPicnickerDebra": {
		"beat": "EVENT_BEAT_PICNICKER_DEBRA",
		"seen": "PicnickerDebraSeenText",
		"beaten": "PicnickerDebraBeatenText"
	},
	"TrainerJugglerFritz": {
		"beat": "EVENT_BEAT_JUGGLER_FRITZ",
		"seen": "JugglerFritzSeenText",
		"beaten": "JugglerFritzBeatenText"
	},
	"TrainerSailorGarrett": {
		"beat": "EVENT_BEAT_SAILOR_GARRETT",
		"seen": "SailorGarrettSeenText",
		"beaten": "SailorGarrettBeatenText"
	},
	"TrainerFisherJonah": {
		"beat": "EVENT_BEAT_FISHER_JONAH",
		"seen": "FisherJonahSeenText",
		"beaten": "FisherJonahBeatenText"
	},
	"TrainerBlackbeltWai": {
		"beat": "EVENT_BEAT_BLACKBELT_WAI",
		"seen": "BlackbeltWaiSeenText",
		"beaten": "BlackbeltWaiBeatenText"
	},
	"TrainerSailorKenneth": {
		"beat": "EVENT_BEAT_SAILOR_KENNETH",
		"seen": "SailorKennethSeenText",
		"beaten": "SailorKennethBeatenText"
	},
	"TrainerTeacherShirley": {
		"beat": "EVENT_BEAT_TEACHER_SHIRLEY",
		"seen": "TeacherShirleySeenText",
		"beaten": "TeacherShirleyBeatenText"
	},
	"TrainerSchoolboyNate": {
		"beat": "EVENT_BEAT_SCHOOLBOY_NATE",
		"seen": "SchoolboyNateSeenText",
		"beaten": "SchoolboyNateBeatenText"
	},
	"TrainerSchoolboyRicky": {
		"beat": "EVENT_BEAT_SCHOOLBOY_RICKY",
		"seen": "SchoolboyRickySeenText",
		"beaten": "SchoolboyRickyBeatenText"
	},
	"TrainerCooltrainermSean": {
		"beat": "EVENT_BEAT_COOLTRAINERM_SEAN",
		"seen": "CooltrainermSeanSeenText",
		"beaten": "CooltrainermSeanBeatenText"
	},
	"TrainerCooltrainerfCarol": {
		"beat": "EVENT_BEAT_COOLTRAINERF_CAROL",
		"seen": "CooltrainerfCarolSeenText",
		"beaten": "CooltrainerfCarolBeatenText"
	},
	"TrainerPokemaniacEthan": {
		"beat": "EVENT_BEAT_POKEMANIAC_ETHAN",
		"seen": "PokemaniacEthanSeenText",
		"beaten": "PokemaniacEthanBeatenText"
	},
	"TrainerHikerNoland": {
		"beat": "EVENT_BEAT_HIKER_NOLAND",
		"seen": "HikerNolandSeenText",
		"beaten": "HikerNolandBeatenText"
	},
	"TrainerGentlemanEdward": {
		"beat": "EVENT_BEAT_GENTLEMAN_EDWARD",
		"seen": "GentlemanEdwardSeenText",
		"beaten": "GentlemanEdwardBeatenText"
	},
	"TrainerBurglarCorey": {
		"beat": "EVENT_BEAT_BURGLAR_COREY",
		"seen": "BurglarCoreySeenText",
		"beaten": "BurglarCoreyBeatenText"
	},
	"TrainerPokefanmColin": {
		"beat": "EVENT_BEAT_POKEFANM_COLIN",
		"seen": "PokefanmColinSeenText",
		"beaten": "PokefanmColinBeatenText"
	},
	"TrainerTwinsMegandpeg1": {
		"beat": "EVENT_BEAT_TWINS_MEG_AND_PEG",
		"seen": "TwinsMegandpeg1SeenText",
		"beaten": "TwinsMegandpeg1BeatenText"
	},
	"TrainerTwinsMegandpeg2": {
		"beat": "EVENT_BEAT_TWINS_MEG_AND_PEG",
		"seen": "TwinsMegandpeg2SeenText",
		"beaten": "TwinsMegandpeg2BeatenText"
	},
	"TrainerPsychicRodney": {
		"beat": "EVENT_BEAT_PSYCHIC_RODNEY",
		"seen": "PsychicRodneySeenText",
		"beaten": "PsychicRodneyBeatenText"
	},
	"TrainerPokefanmJeremy": {
		"beat": "EVENT_BEAT_POKEFANM_JEREMY",
		"seen": "PokefanmJeremySeenText",
		"beaten": "PokefanmJeremyBeatenText"
	},
	"TrainerPokefanfGeorgia": {
		"beat": "EVENT_BEAT_POKEFANF_GEORGIA",
		"seen": "PokefanfGeorgiaSeenText",
		"beaten": "PokefanfGeorgiaBeatenText"
	},
	"TrainerSupernerdShawn": {
		"beat": "EVENT_BEAT_SUPER_NERD_SHAWN",
		"seen": "SupernerdShawnSeenText",
		"beaten": "SupernerdShawnBeatenText"
	},
	"TrainerFirebreatherLyle": {
		"beat": "EVENT_BEAT_FIREBREATHER_LYLE",
		"seen": "FirebreatherLyleSeenText",
		"beaten": "FirebreatherLyleBeatenText"
	},
	"TrainerBugCatcherKen": {
		"beat": "EVENT_BEAT_BUG_CATCHER_KEN",
		"seen": "BugCatcherKenSeenText",
		"beaten": "BugCatcherKenBeatenText"
	},
	"TrainerBeautyCassie": {
		"beat": "EVENT_BEAT_BEAUTY_CASSIE",
		"seen": "BeautyCassieSeenText",
		"beaten": "BeautyCassieBeatenText"
	},
	"TrainerGuitaristClyde": {
		"beat": "EVENT_BEAT_GUITARIST_CLYDE",
		"seen": "GuitaristClydeSeenText",
		"beaten": "GuitaristClydeBeatenText"
	},
	"TrainerLassCarrie": {
		"beat": "EVENT_BEAT_LASS_CARRIE",
		"seen": "LassCarrieSeenText",
		"beaten": "LassCarrieBeatenText"
	},
	"TrainerLassBridget": {
		"beat": "EVENT_BEAT_LASS_BRIDGET",
		"seen": "LassBridgetSeenText",
		"beaten": "LassBridgetBeatenText"
	},
	"TrainerBeautyVictoria": {
		"beat": "EVENT_BEAT_BEAUTY_VICTORIA",
		"seen": "BeautyVictoriaSeenText",
		"beaten": "BeautyVictoriaBeatenText"
	},
	"TrainerBeautySamantha": {
		"beat": "EVENT_BEAT_BEAUTY_SAMANTHA",
		"seen": "BeautySamanthaSeenText",
		"beaten": "BeautySamanthaBeatenText"
	},
	"TrainerSupernerdEric": {
		"beat": "EVENT_BEAT_SUPER_NERD_ERIC",
		"seen": "SupernerdEricSeenText",
		"beaten": "SupernerdEricBeatenText"
	},
	"TrainerSupernerdTeru": {
		"beat": "EVENT_BEAT_SUPER_NERD_TERU",
		"seen": "SupernerdTeruSeenText",
		"beaten": "SupernerdTeruBeatenText"
	},
	"TrainerPokemaniacIssac": {
		"beat": "EVENT_BEAT_POKEMANIAC_ISSAC",
		"seen": "PokemaniacIssacSeenText",
		"beaten": "PokemaniacIssacBeatenText"
	},
	"TrainerPokemaniacDonald": {
		"beat": "EVENT_BEAT_POKEMANIAC_DONALD",
		"seen": "PokemaniacDonaldSeenText",
		"beaten": "PokemaniacDonaldBeatenText"
	},
	"TrainerGruntM11": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_11",
		"seen": "GruntM11SeenText",
		"beaten": "GruntM11BeatenText"
	},
	"TrainerGruntM25": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_25",
		"seen": "GruntM25SeenText",
		"beaten": "GruntM25BeatenText"
	},
	"TrainerBurglarDuncan": {
		"beat": "EVENT_BEAT_BURGLAR_DUNCAN",
		"seen": "BurglarDuncanSeenText",
		"beaten": "BurglarDuncanBeatenText"
	},
	"TrainerBurglarEddie": {
		"beat": "EVENT_BEAT_BURGLAR_EDDIE",
		"seen": "BurglarEddieSeenText",
		"beaten": "BurglarEddieBeatenText"
	},
	"TrainerGruntM13": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_13",
		"seen": "GruntM13SeenText",
		"beaten": "GruntM13BeatenText"
	},
	"TrainerGruntF3": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTF_3",
		"seen": "GruntF3SeenText",
		"beaten": "GruntF3BeatenText"
	},
	"TrainerGruntM24": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_24",
		"seen": "GruntM24SeenText",
		"beaten": "GruntM24BeatenText"
	},
	"TrainerGruntM14": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_14",
		"seen": "GruntM14SeenText",
		"beaten": "GruntM14BeatenText"
	},
	"TrainerGruntM15": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_15",
		"seen": "GruntM15SeenText",
		"beaten": "GruntM15BeatenText"
	},
	"TrainerBugCatcherWayne": {
		"beat": "EVENT_BEAT_BUG_CATCHER_WAYNE",
		"seen": "BugCatcherWayneSeenText",
		"beaten": "BugCatcherWayneBeatenText"
	},
	"TrainerFisherAndre": {
		"beat": "EVENT_BEAT_FISHER_ANDRE",
		"seen": "FisherAndreSeenText",
		"beaten": "FisherAndreBeatenText"
	},
	"TrainerFisherRaymond": {
		"beat": "EVENT_BEAT_FISHER_RAYMOND",
		"seen": "FisherRaymondSeenText",
		"beaten": "FisherRaymondBeatenText"
	},
	"TrainerCooltrainermAaron": {
		"beat": "EVENT_BEAT_COOLTRAINERM_AARON",
		"seen": "CooltrainermAaronSeenText",
		"beaten": "CooltrainermAaronBeatenText"
	},
	"TrainerCooltrainerfLois": {
		"beat": "EVENT_BEAT_COOLTRAINERF_LOIS",
		"seen": "CooltrainerfLoisSeenText",
		"beaten": "CooltrainerfLoisBeatenText"
	},
	"TrainerSkierRoxanne": {
		"beat": "EVENT_BEAT_SKIER_ROXANNE",
		"seen": "SkierRoxanneSeenText",
		"beaten": "SkierRoxanneBeatenText"
	},
	"TrainerSkierClarissa": {
		"beat": "EVENT_BEAT_SKIER_CLARISSA",
		"seen": "SkierClarissaSeenText",
		"beaten": "SkierClarissaBeatenText"
	},
	"TrainerBoarderRonald": {
		"beat": "EVENT_BEAT_BOARDER_RONALD",
		"seen": "BoarderRonaldSeenText",
		"beaten": "BoarderRonaldBeatenText"
	},
	"TrainerBoarderBrad": {
		"beat": "EVENT_BEAT_BOARDER_BRAD",
		"seen": "BoarderBradSeenText",
		"beaten": "BoarderBradBeatenText"
	},
	"TrainerBoarderDouglas": {
		"beat": "EVENT_BEAT_BOARDER_DOUGLAS",
		"seen": "BoarderDouglasSeenText",
		"beaten": "BoarderDouglasBeatenText"
	},
	"TrainerPokemaniacMiller": {
		"beat": "EVENT_BEAT_POKEMANIAC_MILLER",
		"seen": "PokemaniacMillerSeenText",
		"beaten": "PokemaniacMillerBeatenText"
	},
	"TrainerSupernerdMarkus": {
		"beat": "EVENT_BEAT_SUPER_NERD_MARKUS",
		"seen": "SupernerdMarkusSeenText",
		"beaten": "SupernerdMarkusBeatenText"
	},
	"TrainerSupernerdHugh": {
		"beat": "EVENT_BEAT_SUPER_NERD_HUGH",
		"seen": "SupernerdHughSeenText",
		"beaten": "SupernerdHughBeatenText"
	},
	"TrainerSchoolboyJack1": {
		"beat": "EVENT_BEAT_SCHOOLBOY_JACK",
		"seen": "SchoolboyJack1SeenText",
		"beaten": "SchoolboyJack1BeatenText"
	},
	"TrainerPokefanmWilliam": {
		"beat": "EVENT_BEAT_POKEFANM_WILLIAM",
		"seen": "PokefanmWilliamSeenText",
		"beaten": "PokefanmWilliamBeatenText"
	},
	"TrainerPokefanfBeverly1": {
		"beat": "EVENT_BEAT_POKEFANF_BEVERLY",
		"seen": "PokefanfBeverly1SeenText",
		"beaten": "PokefanfBeverly1BeatenText"
	},
	"TrainerLassKrise": {
		"beat": "EVENT_BEAT_LASS_KRISE",
		"seen": "LassKriseSeenText",
		"beaten": "LassKriseBeatenText"
	},
	"TrainerGentlemanAlfred": {
		"beat": "EVENT_BEAT_GENTLEMAN_ALFRED",
		"seen": "GentlemanAlfredSeenText",
		"beaten": "GentlemanAlfredBeatenText"
	},
	"TrainerSailorHuey": {
		"beat": "EVENT_BEAT_SAILOR_HUEY",
		"seen": "SailorHueySeenText",
		"beaten": "SailorHueyBeatenText"
	},
	"TrainerBirdKeeperTheo": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_THEO",
		"seen": "BirdKeeperTheoSeenText",
		"beaten": "BirdKeeperTheoBeatenText"
	},
	"TrainerGentlemanPreston": {
		"beat": "EVENT_BEAT_GENTLEMAN_PRESTON",
		"seen": "GentlemanPrestonSeenText",
		"beaten": "GentlemanPrestonBeatenText"
	},
	"TrainerSailorTerrell": {
		"beat": "EVENT_BEAT_SAILOR_TERRELL",
		"seen": "SailorTerrellSeenText",
		"beaten": "SailorTerrellBeatenText"
	},
	"TrainerLassConnie": {
		"beat": "EVENT_BEAT_LASS_CONNIE",
		"seen": "LassConnie1SeenText",
		"beaten": "LassConnie1BeatenText"
	},
	"TrainerSailorKent": {
		"beat": "EVENT_BEAT_SAILOR_KENT",
		"seen": "SailorKentSeenText",
		"beaten": "SailorKentBeatenText"
	},
	"TrainerBirdKeeperDenis": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_DENIS",
		"seen": "BirdKeeperDenisSeenText",
		"beaten": "BirdKeeperDenisBeatenText"
	},
	"TrainerSailorErnest": {
		"beat": "EVENT_BEAT_SAILOR_ERNEST",
		"seen": "SailorErnestSeenText",
		"beaten": "SailorErnestBeatenText"
	},
	"TrainerCamperJerry": {
		"beat": "EVENT_BEAT_CAMPER_JERRY",
		"seen": "CamperJerrySeenText",
		"beaten": "CamperJerryBeatenText"
	},
	"TrainerGruntM3": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_3",
		"seen": "GruntM3SeenText",
		"beaten": "GruntM3BeatenText"
	},
	"TrainerGruntM4": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_4",
		"seen": "GruntM4SeenText",
		"beaten": "GruntM4BeatenText"
	},
	"TrainerGruntM5": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_5",
		"seen": "GruntM5SeenText",
		"beaten": "GruntM5BeatenText"
	},
	"TrainerGruntM6": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_6",
		"seen": "GruntM6SeenText",
		"beaten": "GruntM6BeatenText"
	},
	"TrainerGruntF2": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTF_2",
		"seen": "GruntF2SeenText",
		"beaten": "GruntF2BeatenText"
	},
	"TrainerGruntM7": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_7",
		"seen": "GruntM7SeenText",
		"beaten": "GruntM7BeatenText"
	},
	"TrainerGruntM8": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_8",
		"seen": "GruntM8SeenText",
		"beaten": "GruntM8BeatenText"
	},
	"TrainerGruntM9": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_9",
		"seen": "GruntM9SeenText",
		"beaten": "GruntM9BeatenText"
	},
	"TrainerScientistMarc": {
		"beat": "EVENT_BEAT_SCIENTIST_MARC",
		"seen": "ScientistMarcSeenText",
		"beaten": "ScientistMarcBeatenText"
	},
	"TrainerGruntM10": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_10",
		"seen": "GruntM10SeenText",
		"beaten": "GruntM10BeatenText"
	},
	"TrainerExecutivem2": {
		"beat": "EVENT_BEAT_ROCKET_EXECUTIVEM_2",
		"seen": "Executivem2SeenText",
		"beaten": "Executivem2BeatenText"
	},
	"TrainerGruntF4": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTF_4",
		"seen": "GruntF4SeenText",
		"beaten": "GruntF4BeatenText"
	},
	"TrainerScientistRich": {
		"beat": "EVENT_BEAT_SCIENTIST_RICH",
		"seen": "ScientistRichSeenText",
		"beaten": "ScientistRichBeatenText"
	},
	"TrainerExecutivef1": {
		"beat": "EVENT_BEAT_ROCKET_EXECUTIVEF_1",
		"seen": "Executivef1SeenText",
		"beaten": "Executivef1BeatenText"
	},
	"TrainerSchoolboyDanny": {
		"beat": "EVENT_BEAT_SCHOOLBOY_DANNY",
		"seen": "SchoolboyDannySeenText",
		"beaten": "SchoolboyDannyBeatenText"
	},
	"TrainerCooltrainerfQuinn": {
		"beat": "EVENT_BEAT_COOLTRAINERF_QUINN",
		"seen": "CooltrainerfQuinnSeenText",
		"beaten": "CooltrainerfQuinnBeatenText"
	},
	"TrainerHikerJim": {
		"beat": "EVENT_BEAT_HIKER_JIM",
		"seen": "HikerJimSeenText",
		"beaten": "HikerJimBeatenText"
	},
	"TrainerPokefanmRobert": {
		"beat": "EVENT_BEAT_POKEFANM_ROBERT",
		"seen": "PokefanmRobertSeenText",
		"beaten": "PokefanmRobertBeatenText"
	},
	"TrainerYoungsterOwen": {
		"beat": "EVENT_BEAT_YOUNGSTER_OWEN",
		"seen": "YoungsterOwenSeenText",
		"beaten": "YoungsterOwenBeatenText"
	},
	"TrainerYoungsterJason": {
		"beat": "EVENT_BEAT_YOUNGSTER_JASON",
		"seen": "YoungsterJasonSeenText",
		"beaten": "YoungsterJasonBeatenText"
	},
	"TrainerPsychicHerman": {
		"beat": "EVENT_BEAT_PSYCHIC_HERMAN",
		"seen": "PsychicHermanSeenText",
		"beaten": "PsychicHermanBeatenText"
	},
	"TrainerPsychicFidel": {
		"beat": "EVENT_BEAT_PSYCHIC_FIDEL",
		"seen": "PsychicFidelSeenText",
		"beaten": "PsychicFidelBeatenText"
	},
	"TrainerFisherKyle": {
		"beat": "EVENT_BEAT_FISHER_KYLE",
		"seen": "FisherKyleSeenText",
		"beaten": "FisherKyleBeatenText"
	},
	"TrainerFisherMartin": {
		"beat": "EVENT_BEAT_FISHER_MARTIN",
		"seen": "FisherMartinSeenText",
		"beaten": "FisherMartinBeatenText"
	},
	"TrainerFisherStephen": {
		"beat": "EVENT_BEAT_FISHER_STEPHEN",
		"seen": "FisherStephenSeenText",
		"beaten": "FisherStephenBeatenText"
	},
	"TrainerFisherBarney": {
		"beat": "EVENT_BEAT_FISHER_BARNEY",
		"seen": "FisherBarneySeenText",
		"beaten": "FisherBarneyBeatenText"
	},
	"TrainerPokefanmAlex": {
		"beat": "EVENT_BEAT_POKEFANM_ALEX",
		"seen": "PokefanmAlexSeenText",
		"beaten": "PokefanmAlexBeatenText"
	},
	"TrainerPokefanmJoshua": {
		"beat": "EVENT_BEAT_POKEFANM_JOSHUA",
		"seen": "PokefanmJoshuaSeenText",
		"beaten": "PokefanmJoshuaBeatenText"
	},
	"TrainerBirdKeeperPerry": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_PERRY",
		"seen": "BirdKeeperPerrySeenText",
		"beaten": "BirdKeeperPerryBeatenText"
	},
	"TrainerBirdKeeperBret": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_BRET",
		"seen": "BirdKeeperBretSeenText",
		"beaten": "BirdKeeperBretBeatenText"
	},
	"TrainerHikerKenny": {
		"beat": "EVENT_BEAT_HIKER_KENNY",
		"seen": "HikerKennySeenText",
		"beaten": "HikerKennyBeatenText"
	},
	"TrainerPokefanmCarter": {
		"beat": "EVENT_BEAT_POKEFANM_CARTER",
		"seen": "PokefanmCarterSeenText",
		"beaten": "PokefanmCarterBeatenText"
	},
	"TrainerBirdKeeperRoy": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_ROY",
		"seen": "BirdKeeperRoySeenText",
		"beaten": "BirdKeeperRoyBeatenText"
	},
	"TrainerPokefanmTrevor": {
		"beat": "EVENT_BEAT_POKEFANM_TREVOR",
		"seen": "PokefanmTrevorSeenText",
		"beaten": "PokefanmTrevorBeatenText"
	},
	"TrainerTeacherColette": {
		"beat": "EVENT_BEAT_TEACHER_COLETTE",
		"seen": "TeacherColetteSeenText",
		"beaten": "TeacherColetteBeatenText"
	},
	"TrainerTeacherHillary": {
		"beat": "EVENT_BEAT_TEACHER_HILLARY",
		"seen": "TeacherHillarySeenText",
		"beaten": "TeacherHillaryBeatenText"
	},
	"TrainerSchoolboyKipp": {
		"beat": "EVENT_BEAT_SCHOOLBOY_KIP",
		"seen": "SchoolboyKippSeenText",
		"beaten": "SchoolboyKippBeatenText"
	},
	"TrainerSchoolboyTommy": {
		"beat": "EVENT_BEAT_SCHOOLBOY_TOMMY",
		"seen": "SchoolboyTommySeenText",
		"beaten": "SchoolboyTommyBeatenText"
	},
	"TrainerSchoolboyJohnny": {
		"beat": "EVENT_BEAT_SCHOOLBOY_JOHNNY",
		"seen": "SchoolboyJohnnySeenText",
		"beaten": "SchoolboyJohnnyBeatenText"
	},
	"TrainerSchoolboyBilly": {
		"beat": "EVENT_BEAT_SCHOOLBOY_BILLY",
		"seen": "SchoolboyBillySeenText",
		"beaten": "SchoolboyBillyBeatenText"
	},
	"TrainerBikerCharles": {
		"beat": "EVENT_BEAT_BIKER_CHARLES",
		"seen": "BikerCharlesSeenText",
		"beaten": "BikerCharlesBeatenText"
	},
	"TrainerBikerRiley": {
		"beat": "EVENT_BEAT_BIKER_RILEY",
		"seen": "BikerRileySeenText",
		"beaten": "BikerRileyBeatenText"
	},
	"TrainerBikerJoel": {
		"beat": "EVENT_BEAT_BIKER_JOEL",
		"seen": "BikerJoelSeenText",
		"beaten": "BikerJoelBeatenText"
	},
	"TrainerBikerGlenn": {
		"beat": "EVENT_BEAT_BIKER_GLENN",
		"seen": "BikerGlennSeenText",
		"beaten": "BikerGlennBeatenText"
	},
	"TrainerBirdKeeperBoris": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_BORIS",
		"seen": "BirdKeeperBorisSeenText",
		"beaten": "BirdKeeperBorisBeatenText"
	},
	"TrainerBirdKeeperBob": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_BOB",
		"seen": "BirdKeeperBobSeenText",
		"beaten": "BirdKeeperBobBeatenText"
	},
	"TrainerSwimmerfDawn": {
		"beat": "EVENT_BEAT_SWIMMERF_DAWN",
		"seen": "SwimmerfDawnSeenText",
		"beaten": "SwimmerfDawnBeatenText"
	},
	"TrainerSwimmermHarold": {
		"beat": "EVENT_BEAT_SWIMMERM_HAROLD",
		"seen": "SwimmermHaroldSeenText",
		"beaten": "SwimmermHaroldBeatenText"
	},
	"TrainerSwimmermJerome": {
		"beat": "EVENT_BEAT_SWIMMERM_JEROME",
		"seen": "SwimmermJeromeSeenText",
		"beaten": "SwimmermJeromeBeatenText"
	},
	"TrainerSwimmermTucker": {
		"beat": "EVENT_BEAT_SWIMMERM_TUCKER",
		"seen": "SwimmermTuckerSeenText",
		"beaten": "SwimmermTuckerBeatenText"
	},
	"TrainerBugCatcherRob": {
		"beat": "EVENT_BEAT_BUG_CATCHER_ROB",
		"seen": "BugCatcherRobSeenText",
		"beaten": "BugCatcherRobBeatenText"
	},
	"TrainerBugCatcherEd": {
		"beat": "EVENT_BEAT_BUG_CATCHER_ED",
		"seen": "BugCatcherEdSeenText",
		"beaten": "BugCatcherEdBeatenText"
	},
	"TrainerBugCatcherDoug": {
		"beat": "EVENT_BEAT_BUG_CATCHER_DOUG",
		"seen": "BugCatcherDougSeenText",
		"beaten": "BugCatcherDougBeatenText"
	},
	"TrainerSwimmerfNicole": {
		"beat": "EVENT_BEAT_SWIMMERF_NICOLE",
		"seen": "SwimmerfNicoleSeenText",
		"beaten": "SwimmerfNicoleBeatenText"
	},
	"TrainerSwimmerfLori": {
		"beat": "EVENT_BEAT_SWIMMERF_LORI",
		"seen": "SwimmerfLoriSeenText",
		"beaten": "SwimmerfLoriBeatenText"
	},
	"TrainerSwimmermCameron": {
		"beat": "EVENT_BEAT_SWIMMERM_CAMERON",
		"seen": "SwimmermCameronSeenText",
		"beaten": "SwimmermCameronBeatenText"
	},
	"TrainerSwimmermSeth": {
		"beat": "EVENT_BEAT_SWIMMERM_SETH",
		"seen": "SwimmermSethSeenText",
		"beaten": "SwimmermSethBeatenText"
	},
	"TrainerSwimmerfNikki": {
		"beat": "EVENT_BEAT_SWIMMERF_NIKKI",
		"seen": "SwimmerfNikkiSeenText",
		"beaten": "SwimmerfNikkiBeatenText"
	},
	"TrainerFisherArnold": {
		"beat": "EVENT_BEAT_FISHER_ARNOLD",
		"seen": "FisherArnoldSeenText",
		"beaten": "FisherArnoldBeatenText"
	},
	"TrainerSchoolboyDudley": {
		"beat": "EVENT_BEAT_SCHOOLBOY_DUDLEY",
		"seen": "SchoolboyDudleySeenText",
		"beaten": "SchoolboyDudleyBeatenText"
	},
	"TrainerLassEllen": {
		"beat": "EVENT_BEAT_LASS_ELLEN",
		"seen": "LassEllenSeenText",
		"beaten": "LassEllenBeatenText"
	},
	"TrainerSchoolboyJoe": {
		"beat": "EVENT_BEAT_SCHOOLBOY_JOE",
		"seen": "SchoolboyJoeSeenText",
		"beaten": "SchoolboyJoeBeatenText"
	},
	"TrainerLassLaura": {
		"beat": "EVENT_BEAT_LASS_LAURA",
		"seen": "LassLauraSeenText",
		"beaten": "LassLauraBeatenText"
	},
	"TrainerCamperLloyd": {
		"beat": "EVENT_BEAT_CAMPER_LLOYD",
		"seen": "CamperLloydSeenText",
		"beaten": "CamperLloydBeatenText"
	},
	"TrainerLassShannon": {
		"beat": "EVENT_BEAT_LASS_SHANNON",
		"seen": "LassShannonSeenText",
		"beaten": "LassShannonBeatenText"
	},
	"TrainerSupernerdPat": {
		"beat": "EVENT_BEAT_SUPER_NERD_PAT",
		"seen": "SupernerdPatSeenText",
		"beaten": "SupernerdPatBeatenText"
	},
	"TrainerCooltrainermJake": {
		"beat": "EVENT_BEAT_COOLTRAINERM_JAKE",
		"seen": "CooltrainermJakeSeenText",
		"beaten": "CooltrainermJakeBeatenText"
	},
	"TrainerCooltrainermGaven3": {
		"beat": "EVENT_BEAT_COOLTRAINERM_GAVEN",
		"seen": "CooltrainermGaven3SeenText",
		"beaten": "CooltrainermGaven3BeatenText"
	},
	"TrainerCooltrainerfJoyce": {
		"beat": "EVENT_BEAT_COOLTRAINERF_JOYCE",
		"seen": "CooltrainerfJoyceSeenText",
		"beaten": "CooltrainerfJoyceBeatenText"
	},
	"TrainerCooltrainerfBeth1": {
		"beat": "EVENT_BEAT_COOLTRAINERF_BETH",
		"seen": "CooltrainerfBeth1SeenText",
		"beaten": "CooltrainerfBeth1BeatenText"
	},
	"TrainerPsychicRichard": {
		"beat": "EVENT_BEAT_PSYCHIC_RICHARD",
		"seen": "PsychicRichardSeenText",
		"beaten": "PsychicRichardBeatenText"
	},
	"TrainerFisherScott": {
		"beat": "EVENT_BEAT_FISHER_SCOTT",
		"seen": "FisherScottSeenText",
		"beaten": "FisherScottBeatenText"
	},
	"TrainerPsychicGilbert": {
		"beat": "EVENT_BEAT_PSYCHIC_GILBERT",
		"seen": "PsychicGilbertSeenText",
		"beaten": "PsychicGilbertBeatenText"
	},
	"TrainerBirdKeeperJose2": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_JOSE2",
		"seen": "BirdKeeperJose2SeenText",
		"beaten": "BirdKeeperJose2BeatenText"
	},
	"TrainerCooltrainermBlake": {
		"beat": "EVENT_BEAT_COOLTRAINERM_BLAKE",
		"seen": "CooltrainermBlakeSeenText",
		"beaten": "CooltrainermBlakeBeatenText"
	},
	"TrainerCooltrainermBrian": {
		"beat": "EVENT_BEAT_COOLTRAINERM_BRIAN",
		"seen": "CooltrainermBrianSeenText",
		"beaten": "CooltrainermBrianBeatenText"
	},
	"TrainerCooltrainerfReena": {
		"beat": "EVENT_BEAT_COOLTRAINERF_REENA",
		"seen": "CooltrainerfReenaSeenText",
		"beaten": "CooltrainerfReenaBeatenText"
	},
	"TrainerCooltrainerfMegan": {
		"beat": "EVENT_BEAT_COOLTRAINERF_MEGAN",
		"seen": "CooltrainerfMeganSeenText",
		"beaten": "CooltrainerfMeganBeatenText"
	},
	"TrainerFirebreatherOtis": {
		"beat": "EVENT_BEAT_FIREBREATHER_OTIS",
		"seen": "FirebreatherOtisSeenText",
		"beaten": "FirebreatherOtisBeatenText"
	},
	"TrainerYoungsterWarren": {
		"beat": "EVENT_BEAT_YOUNGSTER_WARREN",
		"seen": "YoungsterWarrenSeenText",
		"beaten": "YoungsterWarrenBeatenText"
	},
	"TrainerYoungsterJimmy": {
		"beat": "EVENT_BEAT_YOUNGSTER_JIMMY",
		"seen": "YoungsterJimmySeenText",
		"beaten": "YoungsterJimmyBeatenText"
	},
	"TrainerFirebreatherBurt": {
		"beat": "EVENT_BEAT_FIREBREATHER_BURT",
		"seen": "FirebreatherBurtSeenText",
		"beaten": "FirebreatherBurtBeatenText"
	},
	"TrainerYoungsterJoey": {
		"beat": "EVENT_BEAT_YOUNGSTER_JOEY",
		"seen": "YoungsterJoey1SeenText",
		"beaten": "YoungsterJoey1BeatenText"
	},
	"TrainerYoungsterMikey": {
		"beat": "EVENT_BEAT_YOUNGSTER_MIKEY",
		"seen": "YoungsterMikeySeenText",
		"beaten": "YoungsterMikeyBeatenText"
	},
	"TrainerBugCatcherDon": {
		"beat": "EVENT_BEAT_BUG_CATCHER_DON",
		"seen": "BugCatcherDonSeenText",
		"beaten": "BugCatcherDonBeatenText"
	},
	"TrainerBugCatcherWade1": {
		"beat": "EVENT_BEAT_BUG_CATCHER_WADE",
		"seen": "BugCatcherWade1SeenText",
		"beaten": "BugCatcherWade1BeatenText"
	},
	"TrainerCamperRoland": {
		"beat": "EVENT_BEAT_CAMPER_ROLAND",
		"seen": "CamperRolandSeenText",
		"beaten": "CamperRolandBeatenText"
	},
	"TrainerFisherJustin": {
		"beat": "EVENT_BEAT_FISHER_JUSTIN",
		"seen": "FisherJustinSeenText",
		"beaten": "FisherJustinBeatenText"
	},
	"TrainerFisherRalph1": {
		"beat": "EVENT_BEAT_FISHER_RALPH",
		"seen": "FisherRalph1SeenText",
		"beaten": "FisherRalph1BeatenText"
	},
	"TrainerFisherHenry": {
		"beat": "EVENT_BEAT_FISHER_HENRY",
		"seen": "FisherHenrySeenText",
		"beaten": "FisherHenryBeatenText"
	},
	"TrainerPicnickerLiz1": {
		"beat": "EVENT_BEAT_PICNICKER_LIZ",
		"seen": "PicnickerLiz1SeenText",
		"beaten": "PicnickerLiz1BeatenText"
	},
	"TrainerYoungsterAlbert": {
		"beat": "EVENT_BEAT_YOUNGSTER_ALBERT",
		"seen": "YoungsterAlbertSeenText",
		"beaten": "YoungsterAlbertBeatenText"
	},
	"TrainerYoungsterGordon": {
		"beat": "EVENT_BEAT_YOUNGSTER_GORDON",
		"seen": "YoungsterGordonSeenText",
		"beaten": "YoungsterGordonBeatenText"
	},
	"TrainerBirdKeeperPeter": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_PETER",
		"seen": "BirdKeeperPeterSeenText",
		"beaten": "BirdKeeperPeterBeatenText"
	},
	"TrainerHikerAnthony": {
		"beat": "EVENT_BEAT_HIKER_ANTHONY",
		"seen": "HikerAnthony2SeenText",
		"beaten": "HikerAnthony2BeatenText"
	},
	"TrainerCamperTodd1": {
		"beat": "EVENT_BEAT_CAMPER_TODD",
		"seen": "CamperTodd1SeenText",
		"beaten": "CamperTodd1BeatenText"
	},
	"TrainerPicnickerGina1": {
		"beat": "EVENT_BEAT_PICNICKER_GINA",
		"seen": "PicnickerGina1SeenText",
		"beaten": "PicnickerGina1BeatenText"
	},
	"TrainerYoungsterSamuel": {
		"beat": "EVENT_BEAT_YOUNGSTER_SAMUEL",
		"seen": "YoungsterSamuelSeenText",
		"beaten": "YoungsterSamuelBeatenText"
	},
	"TrainerYoungsterIan": {
		"beat": "EVENT_BEAT_YOUNGSTER_IAN",
		"seen": "YoungsterIanSeenText",
		"beaten": "YoungsterIanBeatenText"
	},
	"TrainerPokefanmBrandon": {
		"beat": "EVENT_BEAT_POKEFANM_BRANDON",
		"seen": "PokefanmBrandonSeenText",
		"beaten": "PokefanmBrandonBeatenText"
	},
	"TrainerCooltrainerfIrene": {
		"beat": "EVENT_BEAT_COOLTRAINERF_IRENE",
		"seen": "CooltrainerfIreneSeenText",
		"beaten": "CooltrainerfIreneBeatenText"
	},
	"TrainerCooltrainerfJenn": {
		"beat": "EVENT_BEAT_COOLTRAINERF_JENN",
		"seen": "CooltrainerfJennSeenText",
		"beaten": "CooltrainerfJennBeatenText"
	},
	"TrainerCooltrainerfKate": {
		"beat": "EVENT_BEAT_COOLTRAINERF_KATE",
		"seen": "CooltrainerfKateSeenText",
		"beaten": "CooltrainerfKateBeatenText"
	},
	"TrainerBirdKeeperBryan": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_BRYAN",
		"seen": "BirdKeeperBryanSeenText",
		"beaten": "BirdKeeperBryanBeatenText"
	},
	"TrainerJugglerIrwin": {
		"beat": "EVENT_BEAT_JUGGLER_IRWIN",
		"seen": "JugglerIrwin1SeenText",
		"beaten": "JugglerIrwin1BeatenText"
	},
	"TrainerCamperIvan": {
		"beat": "EVENT_BEAT_CAMPER_IVAN",
		"seen": "CamperIvanSeenText",
		"beaten": "CamperIvanBeatenText"
	},
	"TrainerCamperElliot": {
		"beat": "EVENT_BEAT_CAMPER_ELLIOT",
		"seen": "CamperElliotSeenText",
		"beaten": "CamperElliotBeatenText"
	},
	"TrainerPicnickerBrooke": {
		"beat": "EVENT_BEAT_PICNICKER_BROOKE",
		"seen": "PicnickerBrookeSeenText",
		"beaten": "PicnickerBrookeBeatenText"
	},
	"TrainerPicnickerKim": {
		"beat": "EVENT_BEAT_PICNICKER_KIM",
		"seen": "PicnickerKimSeenText",
		"beaten": "PicnickerKimBeatenText"
	},
	"TrainerBugCatcherArnie": {
		"beat": "EVENT_BEAT_BUG_CATCHER_ARNIE",
		"seen": "BugCatcherArnieSeenText",
		"beaten": "BugCatcherArnieBeatenText"
	},
	"TrainerFirebreatherWalt": {
		"beat": "EVENT_BEAT_FIREBREATHER_WALT",
		"seen": "FirebreatherWaltSeenText",
		"beaten": "FirebreatherWaltBeatenText"
	},
	"TrainerSchoolboyAlan1": {
		"beat": "EVENT_BEAT_SCHOOLBOY_ALAN",
		"seen": "SchoolboyAlan1SeenText",
		"beaten": "SchoolboyAlan1BeatenText"
	},
	"TrainerPsychicMark": {
		"beat": "EVENT_BEAT_PSYCHIC_MARK",
		"seen": "PsychicMarkSeenText",
		"beaten": "PsychicMarkBeatenText"
	},
	"TrainerTwinsAnnandanne1": {
		"beat": "EVENT_BEAT_TWINS_ANN_AND_ANNE",
		"seen": "TwinsAnnandanne1SeenText",
		"beaten": "TwinsAnnandanne1BeatenText"
	},
	"TrainerTwinsAnnandanne2": {
		"beat": "EVENT_BEAT_TWINS_ANN_AND_ANNE",
		"seen": "TwinsAnnandanne2SeenText",
		"beaten": "TwinsAnnandanne2BeatenText"
	},
	"TrainerPsychicGreg": {
		"beat": "EVENT_BEAT_PSYCHIC_GREG",
		"seen": "PsychicGregSeenText",
		"beaten": "PsychicGregBeatenText"
	},
	"TrainerBirdKeeperToby": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_TOBY",
		"seen": "BirdKeeperTobySeenText",
		"beaten": "BirdKeeperTobyBeatenText"
	},
	"TrainerSailorHarry": {
		"beat": "EVENT_BEAT_SAILOR_HARRY",
		"seen": "SailorHarrySeenText",
		"beaten": "SailorHarryBeatenText"
	},
	"TrainerLassDana1": {
		"beat": "EVENT_BEAT_LASS_DANA",
		"seen": "LassDana1SeenText",
		"beaten": "LassDana1BeatenText"
	},
	"TrainerSchoolboyChad1": {
		"beat": "EVENT_BEAT_SCHOOLBOY_CHAD",
		"seen": "SchoolboyChad1SeenText",
		"beaten": "SchoolboyChad1BeatenText"
	},
	"TrainerBeautyValerie": {
		"beat": "EVENT_BEAT_BEAUTY_VALERIE",
		"seen": "BeautyValerieSeenText",
		"beaten": "BeautyValerieBeatenText"
	},
	"TrainerBeautyOlivia": {
		"beat": "EVENT_BEAT_BEAUTY_OLIVIA",
		"seen": "BeautyOliviaSeenText",
		"beaten": "BeautyOliviaBeatenText"
	},
	"TrainerPokefanmDerek": {
		"beat": "EVENT_BEAT_POKEFANM_DEREK",
		"seen": "PokefanmDerekSeenText",
		"beaten": "PokefanmDerekBeatenText"
	},
	"TrainerPokefanfRuth": {
		"beat": "EVENT_BEAT_POKEFANF_RUTH",
		"seen": "PokefanfRuthSeenText",
		"beaten": "PokefanfRuthBeatenText"
	},
	"TrainerSailorEugene": {
		"beat": "EVENT_BEAT_SAILOR_EUGENE",
		"seen": "SailorEugeneSeenText",
		"beaten": "SailorEugeneBeatenText"
	},
	"TrainerPsychicNorman": {
		"beat": "EVENT_BEAT_PSYCHIC_NORMAN",
		"seen": "PsychicNormanSeenText",
		"beaten": "PsychicNormanBeatenText"
	},
	"TrainerBirdKeeperHank": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_HANK",
		"seen": "BirdKeeperHankSeenText",
		"beaten": "BirdKeeperHankBeatenText"
	},
	"TrainerPicnickerHope": {
		"beat": "EVENT_BEAT_PICNICKER_HOPE",
		"seen": "PicnickerHopeSeenText",
		"beaten": "PicnickerHopeBeatenText"
	},
	"TrainerPicnickerSharon": {
		"beat": "EVENT_BEAT_PICNICKER_SHARON",
		"seen": "PicnickerSharonSeenText",
		"beaten": "PicnickerSharonBeatenText"
	},
	"TrainerSwimmerfElaine": {
		"beat": "EVENT_BEAT_SWIMMERF_ELAINE",
		"seen": "SwimmerfElaineSeenText",
		"beaten": "SwimmerfElaineBeatenText"
	},
	"TrainerSwimmerfPaula": {
		"beat": "EVENT_BEAT_SWIMMERF_PAULA",
		"seen": "SwimmerfPaulaSeenText",
		"beaten": "SwimmerfPaulaBeatenText"
	},
	"TrainerSwimmermSimon": {
		"beat": "EVENT_BEAT_SWIMMERM_SIMON",
		"seen": "SwimmermSimonSeenText",
		"beaten": "SwimmermSimonBeatenText"
	},
	"TrainerSwimmermRandall": {
		"beat": "EVENT_BEAT_SWIMMERM_RANDALL",
		"seen": "SwimmermRandallSeenText",
		"beaten": "SwimmermRandallBeatenText"
	},
	"TrainerSwimmerfKaylee": {
		"beat": "EVENT_BEAT_SWIMMERF_KAYLEE",
		"seen": "SwimmerfKayleeSeenText",
		"beaten": "SwimmerfKayleeBeatenText"
	},
	"TrainerSwimmerfSusie": {
		"beat": "EVENT_BEAT_SWIMMERF_SUSIE",
		"seen": "SwimmerfSusieSeenText",
		"beaten": "SwimmerfSusieBeatenText"
	},
	"TrainerSwimmerfDenise": {
		"beat": "EVENT_BEAT_SWIMMERF_DENISE",
		"seen": "SwimmerfDeniseSeenText",
		"beaten": "SwimmerfDeniseBeatenText"
	},
	"TrainerSwimmerfKara": {
		"beat": "EVENT_BEAT_SWIMMERF_KARA",
		"seen": "SwimmerfKaraSeenText",
		"beaten": "SwimmerfKaraBeatenText"
	},
	"TrainerSwimmerfWendy": {
		"beat": "EVENT_BEAT_SWIMMERF_WENDY",
		"seen": "SwimmerfWendySeenText",
		"beaten": "SwimmerfWendyBeatenText"
	},
	"TrainerSwimmermCharlie": {
		"beat": "EVENT_BEAT_SWIMMERM_CHARLIE",
		"seen": "SwimmermCharlieSeenText",
		"beaten": "SwimmermCharlieBeatenText"
	},
	"TrainerSwimmermGeorge": {
		"beat": "EVENT_BEAT_SWIMMERM_GEORGE",
		"seen": "SwimmermGeorgeSeenText",
		"beaten": "SwimmermGeorgeBeatenText"
	},
	"TrainerSwimmermBerke": {
		"beat": "EVENT_BEAT_SWIMMERM_BERKE",
		"seen": "SwimmermBerkeSeenText",
		"beaten": "SwimmermBerkeBeatenText"
	},
	"TrainerSwimmermKirk": {
		"beat": "EVENT_BEAT_SWIMMERM_KIRK",
		"seen": "SwimmermKirkSeenText",
		"beaten": "SwimmermKirkBeatenText"
	},
	"TrainerSwimmermMathew": {
		"beat": "EVENT_BEAT_SWIMMERM_MATHEW",
		"seen": "SwimmermMathewSeenText",
		"beaten": "SwimmermMathewBeatenText"
	},
	"TrainerFisherTully": {
		"beat": "EVENT_BEAT_FISHER_TULLY",
		"seen": "FisherTullySeenText",
		"beaten": "FisherTullyBeatenText"
	},
	"TrainerPokemaniacShane": {
		"beat": "EVENT_BEAT_POKEMANIAC_SHANE",
		"seen": "PokemaniacShaneSeenText",
		"beaten": "PokemaniacShaneBeatenText"
	},
	"TrainerHikerBenjamin": {
		"beat": "EVENT_BEAT_HIKER_BENJAMIN",
		"seen": "HikerBenjaminSeenText",
		"beaten": "HikerBenjaminBeatenText"
	},
	"TrainerCamperSpencer": {
		"beat": "EVENT_BEAT_CAMPER_SPENCER",
		"seen": "CamperSpencerSeenText",
		"beaten": "CamperSpencerBeatenText"
	},
	"TrainerPokemaniacBen": {
		"beat": "EVENT_BEAT_POKEMANIAC_BEN",
		"seen": "PokemaniacBenSeenText",
		"beaten": "PokemaniacBenBeatenText"
	},
	"TrainerPokemaniacBrent": {
		"beat": "EVENT_BEAT_POKEMANIAC_BRENT",
		"seen": "PokemaniacBrentSeenText",
		"beaten": "PokemaniacBrentBeatenText"
	},
	"TrainerPokemaniacRon": {
		"beat": "EVENT_BEAT_POKEMANIAC_RON",
		"seen": "PokemaniacRonSeenText",
		"beaten": "PokemaniacRonBeatenText"
	},
	"TrainerFisherMarvin": {
		"beat": "EVENT_BEAT_FISHER_MARVIN",
		"seen": "FisherMarvinSeenText",
		"beaten": "FisherMarvinBeatenText"
	},
	"TrainerPicnickerTiffany": {
		"beat": "EVENT_BEAT_PICNICKER_TIFFANY",
		"seen": "PicnickerTiffanySeenText",
		"beaten": "PicnickerTiffanyBeatenText"
	},
	"TrainerBirdKeeperVance1": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_VANCE",
		"seen": "BirdKeeperVance1SeenText",
		"beaten": "BirdKeeperVance1BeatenText"
	},
	"TrainerPsychicPhil": {
		"beat": "EVENT_BEAT_PSYCHIC_PHIL",
		"seen": "PsychicPhilSeenText",
		"beaten": "PsychicPhilBeatenText"
	},
	"TrainerFisherWilton1": {
		"beat": "EVENT_BEAT_FISHER_WILTON",
		"seen": "FisherWilton1SeenText",
		"beaten": "FisherWilton1BeatenText"
	},
	"TrainerFisherEdgar": {
		"beat": "EVENT_BEAT_FISHER_EDGAR",
		"seen": "FisherEdgarSeenText",
		"beaten": "FisherEdgarBeatenText"
	},
	"TrainerCooltrainerfCybil": {
		"beat": "EVENT_BEAT_COOLTRAINERF_CYBIL",
		"seen": "CooltrainerfCybilSeenText",
		"beaten": "CooltrainerfCybilBeatenText"
	},
	"TrainerPokemaniacZach": {
		"beat": "EVENT_BEAT_POKEMANIAC_ZACH",
		"seen": "PokemaniacZachSeenText",
		"beaten": "PokemaniacZachBeatenText"
	},
	"TrainerCooltrainermAllen": {
		"beat": "EVENT_BEAT_COOLTRAINERM_ALLEN",
		"seen": "CooltrainermAllenSeenText",
		"beaten": "CooltrainermAllenBeatenText"
	},
	"TrainerBlackbeltKenji": {
		"beat": "EVENT_BEAT_BLACKBELT_KENJI",
		"seen": "BlackbeltKenji3SeenText",
		"beaten": "BlackbeltKenji3BeatenText"
	},
	"TrainerHikerErik": {
		"beat": "EVENT_BEAT_HIKER_ERIK",
		"seen": "HikerErikSeenText",
		"beaten": "HikerErikBeatenText"
	},
	"TrainerHikerMichael": {
		"beat": "EVENT_BEAT_HIKER_MICHAEL",
		"seen": "HikerMichaelSeenText",
		"beaten": "HikerMichaelBeatenText"
	},
	"TrainerHikerParry": {
		"beat": "EVENT_BEAT_HIKER_PARRY",
		"seen": "HikerParry3SeenText",
		"beaten": "HikerParry3BeatenText"
	},
	"TrainerHikerTimothy": {
		"beat": "EVENT_BEAT_HIKER_TIMOTHY",
		"seen": "HikerTimothySeenText",
		"beaten": "HikerTimothyBeatenText"
	},
	"TrainerCooltrainermRyan": {
		"beat": "EVENT_BEAT_COOLTRAINERM_RYAN",
		"seen": "CooltrainermRyanSeenText",
		"beaten": "CooltrainermRyanBeatenText"
	},
	"TrainerCooltrainerfKelly": {
		"beat": "EVENT_BEAT_COOLTRAINERF_KELLY",
		"seen": "CooltrainerfKellySeenText",
		"beaten": "CooltrainerfKellyBeatenText"
	},
	"TrainerCamperTed": {
		"beat": "EVENT_BEAT_CAMPER_TED",
		"seen": "CamperTedSeenText",
		"beaten": "CamperTedBeatenText"
	},
	"TrainerPicnickerErin1": {
		"beat": "EVENT_BEAT_PICNICKER_ERIN",
		"seen": "PicnickerErin1SeenText",
		"beaten": "PicnickerErin1BeatenText"
	},
	"TrainerHikerBailey": {
		"beat": "EVENT_BEAT_HIKER_BAILEY",
		"seen": "HikerBaileySeenText",
		"beaten": "HikerBaileyBeatenText"
	},
	"TrainerPokefanmRex": {
		"beat": "EVENT_BEAT_POKEFANM_REX",
		"seen": "PokefanmRexSeenText",
		"beaten": "PokefanmRexBeatenText"
	},
	"TrainerPokefanmAllan": {
		"beat": "EVENT_BEAT_POKEFANM_ALLAN",
		"seen": "PokefanmAllanSeenText",
		"beaten": "PokefanmAllanBeatenText"
	},
	"TrainerBikerDwayne": {
		"beat": "EVENT_BEAT_BIKER_DWAYNE",
		"seen": "BikerDwayneSeenText",
		"beaten": "BikerDwayneBeatenText"
	},
	"TrainerBikerHarris": {
		"beat": "EVENT_BEAT_BIKER_HARRIS",
		"seen": "BikerHarrisSeenText",
		"beaten": "BikerHarrisBeatenText"
	},
	"TrainerBikerZeke": {
		"beat": "EVENT_BEAT_BIKER_ZEKE",
		"seen": "BikerZekeSeenText",
		"beaten": "BikerZekeBeatenText"
	},
	"TrainerSupernerdSam": {
		"beat": "EVENT_BEAT_SUPER_NERD_SAM",
		"seen": "SupernerdSamSeenText",
		"beaten": "SupernerdSamBeatenText"
	},
	"TrainerSupernerdTom": {
		"beat": "EVENT_BEAT_SUPER_NERD_TOM",
		"seen": "SupernerdTomSeenText",
		"beaten": "SupernerdTomBeatenText"
	},
	"TrainerCamperDean": {
		"beat": "EVENT_BEAT_CAMPER_DEAN",
		"seen": "CamperDeanSeenText",
		"beaten": "CamperDeanBeatenText"
	},
	"TrainerPicnickerHeidi": {
		"beat": "EVENT_BEAT_PICNICKER_HEIDI",
		"seen": "PicnickerHeidiSeenText",
		"beaten": "PicnickerHeidiBeatenText"
	},
	"TrainerCamperSid": {
		"beat": "EVENT_BEAT_CAMPER_SID",
		"seen": "CamperSidSeenText",
		"beaten": "CamperSidBeatenText"
	},
	"TrainerPicnickerEdna": {
		"beat": "EVENT_BEAT_PICNICKER_EDNA",
		"seen": "PicnickerEdnaSeenText",
		"beaten": "PicnickerEdnaBeatenText"
	},
	"TrainerHikerTim": {
		"beat": "EVENT_BEAT_HIKER_TIM",
		"seen": "HikerTimSeenText",
		"beaten": "HikerTimBeatenText"
	},
	"TrainerHikerSidney": {
		"beat": "EVENT_BEAT_HIKER_SIDNEY",
		"seen": "HikerSidneySeenText",
		"beaten": "HikerSidneyBeatenText"
	},
	"TrainerPsychicNathan": {
		"beat": "EVENT_BEAT_PSYCHIC_NATHAN",
		"seen": "PsychicNathanSeenText",
		"beaten": "PsychicNathanBeatenText"
	},
	"TrainerSuperNerdStan": {
		"beat": "EVENT_BEAT_SUPER_NERD_STAN",
		"seen": "SuperNerdStanSeenText",
		"beaten": "SuperNerdStanBeatenText"
	},
	"TrainerMediumRebecca": {
		"beat": "EVENT_BEAT_MEDIUM_REBECCA",
		"seen": "MediumRebeccaSeenText",
		"beaten": "MediumRebeccaBeatenText"
	},
	"TrainerPsychicFranklin": {
		"beat": "EVENT_BEAT_PSYCHIC_FRANKLIN",
		"seen": "PsychicFranklinSeenText",
		"beaten": "PsychicFranklinBeatenText"
	},
	"TrainerMediumDoris": {
		"beat": "EVENT_BEAT_MEDIUM_DORIS",
		"seen": "MediumDorisSeenText",
		"beaten": "MediumDorisBeatenText"
	},
	"TrainerPsychicJared": {
		"beat": "EVENT_BEAT_PSYCHIC_JARED",
		"seen": "PsychicJaredSeenText",
		"beaten": "PsychicJaredBeatenText"
	},
	"TrainerGruntM29": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_29",
		"seen": "GruntM29SeenText",
		"beaten": "GruntM29BeatenText"
	},
	"TrainerGruntM1": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_1",
		"seen": "GruntM1SeenText",
		"beaten": "GruntM1BeatenText"
	},
	"TrainerGruntM2": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_2",
		"seen": "GruntM2SeenText",
		"beaten": "GruntM2BeatenText"
	},
	"TrainerGruntF1": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTF_1",
		"seen": "GruntF1SeenText",
		"beaten": "GruntF1BeatenText"
	},
	"TrainerSageChow": {
		"beat": "EVENT_BEAT_SAGE_CHOW",
		"seen": "SageChowSeenText",
		"beaten": "SageChowBeatenText"
	},
	"TrainerSageNico": {
		"beat": "EVENT_BEAT_SAGE_NICO",
		"seen": "SageNicoSeenText",
		"beaten": "SageNicoBeatenText"
	},
	"TrainerSageEdmond": {
		"beat": "EVENT_BEAT_SAGE_EDMOND",
		"seen": "SageEdmondSeenText",
		"beaten": "SageEdmondBeatenText"
	},
	"TrainerSageJin": {
		"beat": "EVENT_BEAT_SAGE_JIN",
		"seen": "SageJinSeenText",
		"beaten": "SageJinBeatenText"
	},
	"TrainerSageTroy": {
		"beat": "EVENT_BEAT_SAGE_TROY",
		"seen": "SageTroySeenText",
		"beaten": "SageTroyBeatenText"
	},
	"TrainerSageNeal": {
		"beat": "EVENT_BEAT_SAGE_NEAL",
		"seen": "SageNealSeenText",
		"beaten": "SageNealBeatenText"
	},
	"TrainerScientistJed": {
		"beat": "EVENT_BEAT_SCIENTIST_JED",
		"seen": "ScientistJedSeenText",
		"beaten": "ScientistJedBeatenText"
	},
	"TrainerGruntM16": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_16",
		"seen": "GruntM16SeenText",
		"beaten": "GruntM16BeatenText"
	},
	"TrainerGruntM17": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_17",
		"seen": "GruntM17SeenText",
		"beaten": "GruntM17BeatenText"
	},
	"TrainerGruntM18": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_18",
		"seen": "GruntM18SeenText",
		"beaten": "GruntM18BeatenText"
	},
	"TrainerGruntM19": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_19",
		"seen": "GruntM19SeenText",
		"beaten": "GruntM19BeatenText"
	},
	"SlowpokeTailGrunt": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTF_5",
		"seen": "GruntF5SeenText",
		"beaten": "GruntF5BeatenText"
	},
	"RaticateTailGrunt": {
		"beat": "EVENT_BEAT_ROCKET_GRUNTM_28",
		"seen": "GruntM28SeenText",
		"beaten": "GruntM28BeatenText"
	},
	"TrainerScientistRoss": {
		"beat": "EVENT_BEAT_SCIENTIST_ROSS",
		"seen": "ScientistRossSeenText",
		"beaten": "ScientistRossBeatenText"
	},
	"TrainerScientistMitch": {
		"beat": "EVENT_BEAT_SCIENTIST_MITCH",
		"seen": "ScientistMitchSeenText",
		"beaten": "ScientistMitchBeatenText"
	},
	"TrainerPokemaniacLarry": {
		"beat": "EVENT_BEAT_POKEMANIAC_LARRY",
		"seen": "PokemaniacLarrySeenText",
		"beaten": "PokemaniacLarryBeatenText"
	},
	"TrainerHikerRussell": {
		"beat": "EVENT_BEAT_HIKER_RUSSELL",
		"seen": "HikerRussellSeenText",
		"beaten": "HikerRussellBeatenText"
	},
	"TrainerHikerDaniel": {
		"beat": "EVENT_BEAT_HIKER_DANIEL",
		"seen": "HikerDanielSeenText",
		"beaten": "HikerDanielBeatenText"
	},
	"TrainerFirebreatherBill": {
		"beat": "EVENT_BEAT_FIREBREATHER_BILL",
		"seen": "FirebreatherBillSeenText",
		"beaten": "FirebreatherBillBeatenText"
	},
	"TrainerFirebreatherRay": {
		"beat": "EVENT_BEAT_FIREBREATHER_RAY",
		"seen": "FirebreatherRaySeenText",
		"beaten": "FirebreatherRayBeatenText"
	},
	"TrainerPokemaniacAndrew": {
		"beat": "EVENT_BEAT_POKEMANIAC_ANDREW",
		"seen": "PokemaniacAndrewSeenText",
		"beaten": "PokemaniacAndrewBeatenText"
	},
	"TrainerPokemaniacCalvin": {
		"beat": "EVENT_BEAT_POKEMANIAC_CALVIN",
		"seen": "PokemaniacCalvinSeenText",
		"beaten": "PokemaniacCalvinBeatenText"
	},
	"TrainerHikerPhillip": {
		"beat": "EVENT_BEAT_HIKER_PHILLIP",
		"seen": "HikerPhillipSeenText",
		"beaten": "HikerPhillipBeatenText"
	},
	"TrainerHikerLeonard": {
		"beat": "EVENT_BEAT_HIKER_LEONARD",
		"seen": "HikerLeonardSeenText",
		"beaten": "HikerLeonardBeatenText"
	},
	"TrainerCooltrainermNick": {
		"beat": "EVENT_BEAT_COOLTRAINERM_NICK",
		"seen": "CooltrainermNickSeenText",
		"beaten": "CooltrainermNickBeatenText"
	},
	"TrainerCooltrainerfGwen": {
		"beat": "EVENT_BEAT_COOLTRAINERF_GWEN",
		"seen": "CooltrainerfGwenSeenText",
		"beaten": "CooltrainerfGwenBeatenText"
	},
	"TrainerCooltrainerfEmma": {
		"beat": "EVENT_BEAT_COOLTRAINERF_EMMA",
		"seen": "CooltrainerfEmmaSeenText",
		"beaten": "CooltrainerfEmmaBeatenText"
	},
	"TrainerGentlemanGregory": {
		"beat": "EVENT_BEAT_GENTLEMAN_GREGORY",
		"seen": "GentlemanGregorySeenText",
		"beaten": "GentlemanGregoryBeatenText"
	},
	"TrainerGuitaristVincent": {
		"beat": "EVENT_BEAT_GUITARIST_VINCENT",
		"seen": "GuitaristVincentSeenText",
		"beaten": "GuitaristVincentBeatenText"
	},
	"TrainerJugglerHorton": {
		"beat": "EVENT_BEAT_JUGGLER_HORTON",
		"seen": "JugglerHortonSeenText",
		"beaten": "JugglerHortonBeatenText"
	},
	"TrainerBirdKeeperRod": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_ROD",
		"seen": "BirdKeeperRodSeenText",
		"beaten": "BirdKeeperRodBeatenText"
	},
	"TrainerBirdKeeperAbe": {
		"beat": "EVENT_BEAT_BIRD_KEEPER_ABE",
		"seen": "BirdKeeperAbeSeenText",
		"beaten": "BirdKeeperAbeBeatenText"
	},
	"TrainerSageGaku": {
		"beat": "EVENT_BEAT_SAGE_GAKU",
		"seen": "SageGakuSeenText",
		"beaten": "SageGakuBeatenText"
	},
	"TrainerSageMasa": {
		"beat": "EVENT_BEAT_SAGE_MASA",
		"seen": "SageMasaSeenText",
		"beaten": "SageMasaBeatenText"
	},
	"TrainerSageKoji": {
		"beat": "EVENT_BEAT_SAGE_KOJI",
		"seen": "SageKojiSeenText",
		"beaten": "SageKojiBeatenText"
	}
};

// the header for a trainer event on the CURRENT map, or null. Crystal maps only:
// the Kanto/Hoenn decomp scripts put the battle in the label itself.
export function crystalTrainerHeader(world, script) {
	if (!script || !world || !world.current || !world.current.map || !world.current.map._crystal_tileset) return null;
	return CRYSTAL_TRAINER_HEADERS[script] || null;
}
