// GENERATED by tools/gen_divewarps.mjs from the decomps' setdivewarp — do not edit.
// { <map stem>: [ { map, x, y, at? } ] } — see divelinks.js
export const DIVE_WARPS = {
	"AbandonedShip_Corridors_B1F": [
		{
			"map": "MAP_ABANDONED_SHIP_UNDERWATER1",
			"x": 5,
			"y": 4
		}
	],
	"AbandonedShip_HiddenFloorCorridors": [
		{
			"map": "MAP_ABANDONED_SHIP_UNDERWATER1",
			"x": 5,
			"y": 4
		}
	],
	"AbandonedShip_Rooms_B1F": [
		{
			"map": "MAP_ABANDONED_SHIP_UNDERWATER2",
			"x": 17,
			"y": 4
		}
	],
	"AbandonedShip_Underwater1": [
		{
			"map": "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS",
			"x": 0,
			"y": 10
		}
	],
	"AbandonedShip_Underwater2": [
		{
			"map": "MAP_ABANDONED_SHIP_ROOMS_B1F",
			"x": 13,
			"y": 7
		}
	],
	"MarineCave_Entrance": [
		{
			"map": "MAP_UNDERWATER_MARINE_CAVE",
			"x": 9,
			"y": 6
		}
	],
	"Hoenn2_MarineCave_Entrance": [
		{
			"map": "MAP_HOENN2_UNDERWATER_MARINE_CAVE",
			"x": 9,
			"y": 6
		}
	],
	"Route134": [
		{
			"map": "MAP_UNDERWATER_ROUTE134",
			"x": 8,
			"y": 6
		}
	],
	"SeafloorCavern_Entrance": [
		{
			"map": "MAP_UNDERWATER_SEAFLOOR_CAVERN",
			"x": 6,
			"y": 5
		}
	],
	"SealedChamber_OuterRoom": [
		{
			"map": "MAP_UNDERWATER_SEALED_CHAMBER",
			"x": 12,
			"y": 44
		}
	],
	"SootopolisCity": [
		{
			"map": "MAP_UNDERWATER_SOOTOPOLIS_CITY",
			"x": 9,
			"y": 6
		}
	],
	"Hoenn2_SootopolisCity": [
		{
			"map": "MAP_HOENN2_UNDERWATER_SOOTOPOLIS_CITY",
			"x": 9,
			"y": 6
		}
	],
	"Underwater_MarineCave": [
		{
			"map": "MAP_MARINE_CAVE_ENTRANCE",
			"x": 10,
			"y": 17
		}
	],
	"Hoenn2_Underwater_MarineCave": [
		{
			"map": "MAP_HOENN2_MARINE_CAVE_ENTRANCE",
			"x": 10,
			"y": 17
		}
	],
	"Underwater_Route134": [
		{
			"map": "MAP_ROUTE134",
			"x": 60,
			"y": 31
		}
	],
	"Underwater_SeafloorCavern": [
		{
			"map": "MAP_SEAFLOOR_CAVERN_ENTRANCE",
			"x": 10,
			"y": 17
		}
	],
	"Underwater_SealedChamber": [
		{
			"map": "MAP_SEALED_CHAMBER_OUTER_ROOM",
			"x": 10,
			"y": 19,
			"at": [
				12,
				44
			]
		},
		{
			"map": "MAP_ROUTE134",
			"x": 60,
			"y": 31
		}
	],
	"Underwater_SootopolisCity": [
		{
			"map": "MAP_SOOTOPOLIS_CITY",
			"x": 29,
			"y": 53
		}
	],
	"Hoenn2_Underwater_SootopolisCity": [
		{
			"map": "MAP_HOENN2_SOOTOPOLIS_CITY",
			"x": 29,
			"y": 53
		}
	]
};
