// encounters_postgame.js — JOHKANTO's postgame roster. GENERATED by
// tools/gen_postgame_encounters.mjs; re-run it rather than editing by hand.
//
// Every species the rest of the game leaves uncatchable lives here. The coverage
// report (Plans/SPECIES_COVERAGE.md) found 298 ordinary evolution ROOTS with no
// home anywhere; placing a root is enough, because evolution and breeding closure
// carry the rest of each line.
//
// Laid out by GYM. JohKanto's eight are Gen-2 Kanto's, and between them their
// types cover all eighteen, so "every mon is catchable somewhere" holds by
// construction:
//   Brock rock/ground/steel · Misty water/ice · Surge electric/flying
//   Erika grass/bug · Janine poison/dark · Sabrina psychic/fairy
//   Blaine fire/dragon · Blue normal/fighting/ghost
//
// A land map carries three 7-slot rosters (morning/day/night), so time of day is
// real capacity and a route holds up to 21 species without becoming a soup.
// Levels run 50-77 by gym order: this is post-Champion content.
//
// encounters.js consults this FIRST, ahead of DAYNIGHT and the base table. It has
// to be a separate module: all 23 JohKanto maps with a land table are already in
// encounters_daynight.js, which wins for land, so adding these to the base table
// would have been inert — and encounters_daynight.js is itself generated from
// pokecrystal, so writing here would be eaten by the next regeneration.
export const POSTGAME = {
	'MAP_JOHKANTO_CERULEAN_CITY': {
		water: [{id:'goldeen',min:53,max:55,w:60},{id:'goldeen',min:53,max:55,w:30},{id:'wishiwashi',min:53,max:56,w:5},{id:'dewpider',min:53,max:56,w:4},{id:'bergmite',min:54,max:57,w:1}],
	},
	'MAP_JOHKANTO_CINNABAR_ISLAND': {
		fishing: [{id:'magikarp',min:68,max:70,w:70},{id:'magikarp',min:68,max:70,w:30},{id:'magikarp',min:68,max:70,w:35},{id:'tentacool',min:68,max:70,w:35},{id:'chinchou',min:68,max:70,w:20},{id:'pansear',min:71,max:74,w:40},{id:'litleo',min:72,max:75,w:40},{id:'druddigon',min:73,max:76,w:15},{id:'chinchou',min:68,max:70,w:8},{id:'chinchou',min:68,max:70,w:8}],
	},
	'MAP_JOHKANTO_POWER_PLANT': {
		land: {
			morning: [{id:'pawmi',min:56,max:59,w:10},{id:'emolga',min:59,max:62,w:5},{id:'audino',min:60,max:64,w:4}],
			day: [{id:'toxel',min:56,max:59,w:10},{id:'dedenne',min:59,max:62,w:5},{id:'terapagos',min:60,max:64,w:4}],
			night: [{id:'noibat',min:56,max:59,w:10},{id:'togedemaru',min:59,max:62,w:5},{id:'zangoose',min:60,max:64,w:4}],
		},
	},
	'MAP_JOHKANTO_ROCK_TUNNEL_1F': {
		land: {
			morning: [{id:'cubone',min:50,max:52,w:30},{id:'geodude',min:50,max:52,w:30},{id:'machop',min:50,max:52,w:20},{id:'bronzor',min:51,max:54,w:10},{id:'cranidos',min:52,max:55,w:5},{id:'stunfisk',min:54,max:57,w:4},{id:'tsareena',min:54,max:58,w:1}],
			day: [{id:'cubone',min:50,max:52,w:30},{id:'geodude',min:50,max:52,w:30},{id:'machop',min:50,max:52,w:20},{id:'klink',min:51,max:54,w:10},{id:'shieldon',min:53,max:56,w:5},{id:'orthworm',min:54,max:57,w:4},{id:'yanmega',min:54,max:58,w:1}],
			night: [{id:'zubat',min:50,max:52,w:30},{id:'geodude',min:50,max:52,w:30},{id:'geodude',min:50,max:52,w:20},{id:'meltan',min:51,max:54,w:10},{id:'glimmet',min:53,max:56,w:5},{id:'runerigus',min:54,max:57,w:4},{id:'tangrowth',min:54,max:58,w:1}],
		},
	},
	'MAP_JOHKANTO_ROCK_TUNNEL_B1F': {
		land: {
			morning: [{id:'cubone',min:50,max:52,w:30},{id:'geodude',min:50,max:52,w:30},{id:'onix',min:50,max:52,w:20},{id:'varoom',min:51,max:54,w:10},{id:'tyrunt',min:53,max:56,w:5},{id:'carbink',min:54,max:57,w:4},{id:'hydrapple',min:54,max:58,w:1}],
			day: [{id:'cubone',min:50,max:52,w:30},{id:'geodude',min:50,max:52,w:30},{id:'onix',min:50,max:52,w:20},{id:'golett',min:51,max:54,w:10},{id:'amaura',min:53,max:56,w:5},{id:'minior',min:54,max:57,w:4},{id:'ogerpon',min:54,max:58,w:1}],
			night: [{id:'zubat',min:50,max:52,w:30},{id:'geodude',min:50,max:52,w:30},{id:'onix',min:50,max:52,w:20},{id:'binacle',min:51,max:54,w:10},{id:'mudbray',min:53,max:56,w:5},{id:'probopass',min:55,max:58,w:4},{id:'golbat',min:50,max:52,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_1': {
		land: {
			morning: [{id:'pidgey',min:71,max:73,w:30},{id:'rattata',min:71,max:73,w:30},{id:'sentret',min:71,max:73,w:20},{id:'litwick',min:71,max:74,w:10},{id:'timburr',min:72,max:75,w:5},{id:'crabrawler',min:73,max:76,w:4},{id:'sawk',min:74,max:77,w:1}],
			day: [{id:'pidgey',min:71,max:73,w:30},{id:'rattata',min:71,max:73,w:30},{id:'sentret',min:71,max:73,w:20},{id:'meditite',min:71,max:74,w:10},{id:'sinistea',min:72,max:75,w:5},{id:'drifloon',min:73,max:76,w:4},{id:'falinks',min:74,max:77,w:1}],
			night: [{id:'hoothoot',min:71,max:73,w:30},{id:'rattata',min:71,max:73,w:30},{id:'rattata',min:71,max:73,w:20},{id:'riolu',min:71,max:74,w:10},{id:'phantump',min:72,max:75,w:5},{id:'pancham',min:73,max:76,w:4},{id:'mimikyu',min:74,max:77,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_10_NORTH': {
		land: {
			morning: [{id:'spearow',min:56,max:58,w:30},{id:'voltorb',min:56,max:58,w:30},{id:'raticate',min:56,max:58,w:20},{id:'helioptile',min:58,max:61,w:10},{id:'flamigo',min:61,max:64,w:5},{id:'lickilicky',min:60,max:64,w:4},{id:'electabuzz',min:56,max:58,w:1}],
			day: [{id:'spearow',min:56,max:58,w:30},{id:'voltorb',min:56,max:58,w:30},{id:'raticate',min:56,max:58,w:20},{id:'blitzle',min:58,max:61,w:10},{id:'dracozolt',min:61,max:64,w:5},{id:'farigiraf',min:60,max:64,w:4},{id:'electabuzz',min:56,max:58,w:1}],
			night: [{id:'venonat',min:56,max:58,w:30},{id:'voltorb',min:56,max:58,w:30},{id:'raticate',min:56,max:58,w:20},{id:'pachirisu',min:58,max:61,w:10},{id:'arctozolt',min:61,max:64,w:5},{id:'dudunsparce',min:60,max:64,w:4},{id:'electabuzz',min:56,max:58,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_11': {
		land: {
			morning: [{id:'hoppip',min:56,max:58,w:30},{id:'raticate',min:56,max:58,w:30},{id:'magnemite',min:56,max:58,w:20},{id:'tadbulb',min:57,max:60,w:10},{id:'cramorant',min:60,max:63,w:5},{id:'drampa',min:60,max:64,w:4},{id:'hoppip',min:56,max:58,w:1}],
			day: [{id:'hoppip',min:56,max:58,w:30},{id:'raticate',min:56,max:58,w:30},{id:'magnemite',min:56,max:58,w:20},{id:'tynamo',min:58,max:61,w:10},{id:'bombirdier',min:60,max:63,w:5},{id:'bouffalant',min:60,max:64,w:4},{id:'hoppip',min:56,max:58,w:1}],
			night: [{id:'drowzee',min:56,max:58,w:30},{id:'meowth',min:56,max:58,w:30},{id:'magnemite',min:56,max:58,w:20},{id:'wattrel',min:58,max:61,w:10},{id:'pawmot',min:60,max:63,w:5},{id:'oranguru',min:60,max:64,w:4},{id:'hypno',min:56,max:58,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_13': {
		land: {
			morning: [{id:'nidorino',min:62,max:64,w:30},{id:'nidorina',min:62,max:64,w:30},{id:'pidgeotto',min:62,max:64,w:20},{id:'nickit',min:62,max:65,w:10},{id:'salandit',min:64,max:67,w:5},{id:'poipole',min:65,max:68,w:4},{id:'chansey',min:62,max:64,w:1}],
			day: [{id:'nidorino',min:62,max:64,w:30},{id:'nidorina',min:62,max:64,w:30},{id:'pidgeotto',min:62,max:64,w:20},{id:'impidimp',min:62,max:65,w:10},{id:'stunky',min:64,max:67,w:5},{id:'clodsire',min:66,max:69,w:4},{id:'chansey',min:62,max:64,w:1}],
			night: [{id:'venonat',min:62,max:64,w:30},{id:'quagsire',min:62,max:64,w:30},{id:'noctowl',min:62,max:64,w:20},{id:'purrloin',min:62,max:65,w:10},{id:'trubbish',min:64,max:67,w:5},{id:'overqwil',min:66,max:69,w:4},{id:'chansey',min:62,max:64,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_14': {
		land: {
			morning: [{id:'nidorino',min:62,max:64,w:30},{id:'nidorina',min:62,max:64,w:30},{id:'pidgeotto',min:62,max:64,w:20},{id:'inkay',min:63,max:66,w:10},{id:'skorupi',min:64,max:67,w:5},{id:'obstagoon',min:66,max:69,w:4},{id:'chansey',min:62,max:64,w:1}],
			day: [{id:'nidorino',min:62,max:64,w:30},{id:'nidorina',min:62,max:64,w:30},{id:'pidgeotto',min:62,max:64,w:20},{id:'shroodle',min:63,max:66,w:10},{id:'zorua',min:65,max:68,w:5},{id:'naganadel',min:66,max:69,w:4},{id:'chansey',min:62,max:64,w:1}],
			night: [{id:'venonat',min:62,max:64,w:30},{id:'quagsire',min:62,max:64,w:30},{id:'noctowl',min:62,max:64,w:20},{id:'croagunk',min:63,max:66,w:10},{id:'pawniard',min:65,max:68,w:5},{id:'kingambit',min:66,max:69,w:4},{id:'chansey',min:62,max:64,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_15': {
		land: {
			morning: [{id:'nidorino',min:62,max:64,w:30},{id:'nidorina',min:62,max:64,w:30},{id:'pidgeotto',min:62,max:64,w:20},{id:'deino',min:63,max:66,w:10},{id:'maschiff',min:65,max:68,w:5},{id:'okidogi',min:67,max:70,w:4},{id:'chansey',min:62,max:64,w:1}],
			day: [{id:'nidorino',min:62,max:64,w:30},{id:'nidorina',min:62,max:64,w:30},{id:'pidgeotto',min:62,max:64,w:20},{id:'mareanie',min:63,max:66,w:10},{id:'scraggy',min:65,max:68,w:5},{id:'munkidori',min:67,max:70,w:4},{id:'chansey',min:62,max:64,w:1}],
			night: [{id:'venonat',min:62,max:64,w:30},{id:'quagsire',min:62,max:64,w:30},{id:'noctowl',min:62,max:64,w:20},{id:'skrelp',min:64,max:67,w:10},{id:'vullaby',min:65,max:68,w:5},{id:'fezandipiti',min:67,max:70,w:4},{id:'chansey',min:62,max:64,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_16': {
		land: {
			morning: [{id:'grimer',min:59,max:61,w:30},{id:'fearow',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'bounsweet',min:59,max:62,w:10},{id:'rellor',min:60,max:63,w:5},{id:'shelmet',min:62,max:65,w:4},{id:'dwebble',min:63,max:66,w:1}],
			day: [{id:'grimer',min:59,max:61,w:30},{id:'fearow',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'tarountula',min:59,max:62,w:10},{id:'cherubi',min:61,max:64,w:5},{id:'snivy',min:62,max:65,w:4},{id:'snover',min:63,max:66,w:1}],
			night: [{id:'grimer',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'nymble',min:59,max:62,w:10},{id:'bramblin',min:61,max:64,w:5},{id:'poltchageist',min:62,max:65,w:4},{id:'skiddo',min:63,max:66,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_17': {
		land: {
			morning: [{id:'fearow',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'burmy',min:60,max:63,w:10},{id:'budew',min:61,max:64,w:5},{id:'sewaddle',min:62,max:65,w:4},{id:'larvesta',min:63,max:66,w:1}],
			day: [{id:'fearow',min:59,max:61,w:30},{id:'slugma',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'wimpod',min:60,max:63,w:10},{id:'cottonee',min:61,max:64,w:5},{id:'grookey',min:62,max:65,w:4},{id:'carnivine',min:63,max:66,w:1}],
			night: [{id:'grimer',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'combee',min:60,max:63,w:10},{id:'petilil',min:61,max:64,w:5},{id:'sprigatito',min:62,max:65,w:4},{id:'maractus',min:63,max:66,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_18': {
		land: {
			morning: [{id:'grimer',min:59,max:61,w:30},{id:'fearow',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'fomantis',min:60,max:63,w:10},{id:'morelull',min:61,max:64,w:5},{id:'chespin',min:62,max:65,w:4},{id:'rabsca',min:63,max:66,w:1}],
			day: [{id:'grimer',min:59,max:61,w:30},{id:'fearow',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'gossifleur',min:60,max:63,w:10},{id:'foongus',min:61,max:64,w:5},{id:'karrablast',min:62,max:65,w:4},{id:'brambleghast',min:63,max:66,w:1}],
			night: [{id:'grimer',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:30},{id:'grimer',min:59,max:61,w:20},{id:'venipede',min:60,max:63,w:10},{id:'grubbin',min:61,max:64,w:5},{id:'pansage',min:62,max:65,w:4},{id:'durant',min:63,max:66,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_19': {
		fishing: [{id:'magikarp',min:68,max:70,w:70},{id:'magikarp',min:68,max:70,w:30},{id:'magikarp',min:68,max:70,w:35},{id:'krabby',min:68,max:70,w:35},{id:'krabby',min:68,max:70,w:20},{id:'axew',min:71,max:74,w:40},{id:'tatsugiri',min:72,max:75,w:40},{id:'turtonator',min:73,max:76,w:15},{id:'krabby',min:68,max:70,w:8},{id:'krabby',min:68,max:70,w:8}],
	},
	'MAP_JOHKANTO_ROUTE_2': {
		land: {
			morning: [{id:'caterpie',min:50,max:52,w:30},{id:'ledyba',min:50,max:52,w:30},{id:'pidgey',min:50,max:52,w:20},{id:'rolycoly',min:50,max:53,w:10},{id:'silicobra',min:52,max:55,w:5},{id:'archen',min:53,max:56,w:4},{id:'duraludon',min:55,max:58,w:1}],
			day: [{id:'caterpie',min:50,max:52,w:30},{id:'pidgey',min:50,max:52,w:30},{id:'pidgey',min:50,max:52,w:20},{id:'roggenrola',min:50,max:53,w:10},{id:'honedge',min:52,max:55,w:5},{id:'perrserker',min:53,max:56,w:4},{id:'ursaluna',min:55,max:58,w:1}],
			night: [{id:'hoothoot',min:50,max:52,w:30},{id:'spinarak',min:50,max:52,w:30},{id:'hoothoot',min:50,max:52,w:20},{id:'rockruff',min:50,max:53,w:10},{id:'drilbur',min:52,max:55,w:5},{id:'klawf',min:53,max:56,w:4},{id:'gholdengo',min:55,max:58,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_20': {
		fishing: [{id:'magikarp',min:68,max:70,w:70},{id:'magikarp',min:68,max:70,w:30},{id:'magikarp',min:68,max:70,w:35},{id:'tentacool',min:68,max:70,w:35},{id:'chinchou',min:68,max:70,w:20},{id:'litten',min:71,max:74,w:40},{id:'oricorio',min:72,max:75,w:40},{id:'cyclizar',min:73,max:76,w:15},{id:'chinchou',min:68,max:70,w:8},{id:'chinchou',min:68,max:70,w:8}],
	},
	'MAP_JOHKANTO_ROUTE_21': {
		land: {
			morning: [{id:'tangela',min:68,max:70,w:30},{id:'rattata',min:68,max:70,w:30},{id:'tangela',min:68,max:70,w:20},{id:'charcadet',min:68,max:71,w:10},{id:'goomy',min:69,max:72,w:5},{id:'fennekin',min:69,max:72,w:4},{id:'scorbunny',min:70,max:73,w:1}],
			day: [{id:'tangela',min:68,max:70,w:30},{id:'rattata',min:68,max:70,w:30},{id:'tangela',min:68,max:70,w:20},{id:'dreepy',min:68,max:71,w:10},{id:'jangmoo',min:69,max:72,w:5},{id:'tepig',min:70,max:73,w:4},{id:'fuecoco',min:70,max:73,w:1}],
			night: [{id:'tangela',min:68,max:70,w:30},{id:'rattata',min:68,max:70,w:30},{id:'tangela',min:68,max:70,w:20},{id:'gible',min:68,max:71,w:10},{id:'sizzlipede',min:69,max:72,w:5},{id:'chimchar',min:70,max:73,w:4},{id:'darumaka',min:71,max:74,w:1}],
		},
		fishing: [{id:'magikarp',min:68,max:70,w:70},{id:'magikarp',min:68,max:70,w:30},{id:'magikarp',min:68,max:70,w:35},{id:'tentacool',min:68,max:70,w:35},{id:'chinchou',min:68,max:70,w:20},{id:'frigibax',min:71,max:74,w:40},{id:'heatmor',min:72,max:75,w:40},{id:'chinchou',min:68,max:70,w:8},{id:'chinchou',min:68,max:70,w:8},{id:'chinchou',min:68,max:70,w:8}],
	},
	'MAP_JOHKANTO_ROUTE_22': {
		land: {
			morning: [{id:'rattata',min:71,max:73,w:30},{id:'spearow',min:71,max:73,w:30},{id:'spearow',min:71,max:73,w:20},{id:'greavard',min:72,max:75,w:10},{id:'clobbopus',min:73,max:76,w:5},{id:'mienfoo',min:74,max:77,w:4},{id:'grapploct',min:75,max:78,w:1}],
			day: [{id:'rattata',min:71,max:73,w:30},{id:'spearow',min:71,max:73,w:30},{id:'spearow',min:71,max:73,w:20},{id:'gimmighoul',min:72,max:75,w:10},{id:'sandygast',min:73,max:76,w:5},{id:'kubfu',min:74,max:77,w:4},{id:'spiritomb',min:75,max:78,w:1}],
			night: [{id:'rattata',min:71,max:73,w:30},{id:'poliwag',min:71,max:73,w:30},{id:'rattata',min:71,max:73,w:20},{id:'yamask',min:72,max:75,w:10},{id:'pumpkaboo',min:73,max:76,w:5},{id:'throh',min:74,max:77,w:4},{id:'passimian',min:75,max:78,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_24': {
		land: {
			morning: [{id:'caterpie',min:53,max:55,w:30},{id:'caterpie',min:53,max:55,w:30},{id:'metapod',min:53,max:55,w:20},{id:'alomomola',min:57,max:60,w:10},{id:'bunnelby',min:57,max:61,w:5},{id:'minccino',min:57,max:61,w:4},{id:'butterfree',min:53,max:55,w:1}],
			day: [{id:'caterpie',min:53,max:55,w:30},{id:'sunkern',min:53,max:55,w:30},{id:'caterpie',min:53,max:55,w:20},{id:'eiscue',min:57,max:60,w:10},{id:'starly',min:57,max:61,w:5},{id:'tandemaus',min:57,max:61,w:4},{id:'butterfree',min:53,max:55,w:1}],
			night: [{id:'venonat',min:53,max:55,w:30},{id:'oddish',min:53,max:55,w:30},{id:'oddish',min:53,max:55,w:20},{id:'bruxish',min:57,max:60,w:10},{id:'bidoof',min:57,max:61,w:5},{id:'glameow',min:57,max:61,w:4},{id:'gloom',min:53,max:55,w:1}],
		},
		water: [{id:'goldeen',min:53,max:55,w:60},{id:'goldeen',min:53,max:55,w:30},{id:'snom',min:53,max:56,w:5},{id:'arrokuda',min:54,max:57,w:4},{id:'ducklett',min:54,max:57,w:1}],
		fishing: [{id:'magikarp',min:53,max:55,w:70},{id:'magikarp',min:53,max:55,w:30},{id:'magikarp',min:53,max:55,w:35},{id:'goldeen',min:53,max:55,w:35},{id:'goldeen',min:53,max:55,w:20},{id:'oshawott',min:54,max:57,w:40},{id:'piplup',min:55,max:58,w:40},{id:'panpour',min:55,max:58,w:15},{id:'buizel',min:56,max:59,w:4},{id:'cetoddle',min:56,max:59,w:1}],
	},
	'MAP_JOHKANTO_ROUTE_25': {
		land: {
			morning: [{id:'caterpie',min:53,max:55,w:30},{id:'pidgey',min:53,max:55,w:30},{id:'pidgeotto',min:53,max:55,w:20},{id:'veluza',min:57,max:60,w:10},{id:'yungoos',min:57,max:61,w:5},{id:'deerling',min:57,max:61,w:4},{id:'butterfree',min:53,max:55,w:1}],
			day: [{id:'caterpie',min:53,max:55,w:30},{id:'pidgey',min:53,max:55,w:30},{id:'pidgeotto',min:53,max:55,w:20},{id:'phione',min:57,max:60,w:10},{id:'lechonk',min:57,max:61,w:5},{id:'stufful',min:57,max:61,w:4},{id:'butterfree',min:53,max:55,w:1}],
			night: [{id:'oddish',min:53,max:55,w:30},{id:'hoothoot',min:53,max:55,w:30},{id:'venonat',min:53,max:55,w:20},{id:'dracovish',min:57,max:60,w:10},{id:'patrat',min:57,max:61,w:5},{id:'buneary',min:57,max:61,w:4},{id:'noctowl',min:53,max:55,w:1}],
		},
		water: [{id:'goldeen',min:53,max:55,w:60},{id:'goldeen',min:53,max:55,w:30},{id:'feebas',min:53,max:56,w:5},{id:'chewtle',min:54,max:57,w:4},{id:'vanillite',min:54,max:57,w:1}],
		fishing: [{id:'magikarp',min:53,max:55,w:70},{id:'magikarp',min:53,max:55,w:30},{id:'magikarp',min:53,max:55,w:35},{id:'goldeen',min:53,max:55,w:35},{id:'goldeen',min:53,max:55,w:20},{id:'sobble',min:55,max:58,w:40},{id:'froakie',min:55,max:58,w:40},{id:'popplio',min:55,max:58,w:15},{id:'finneon',min:56,max:59,w:4},{id:'frillish',min:56,max:59,w:1}],
	},
	'MAP_JOHKANTO_ROUTE_3': {
		land: {
			morning: [{id:'spearow',min:50,max:52,w:30},{id:'rattata',min:50,max:52,w:30},{id:'ekans',min:50,max:52,w:20},{id:'nacli',min:50,max:53,w:10},{id:'hippopotas',min:52,max:55,w:5},{id:'lunatone',min:54,max:57,w:4},{id:'wyrdeer',min:54,max:58,w:1}],
			day: [{id:'spearow',min:50,max:52,w:30},{id:'rattata',min:50,max:52,w:30},{id:'ekans',min:50,max:52,w:20},{id:'bonsly',min:51,max:54,w:10},{id:'cufant',min:52,max:55,w:5},{id:'klefki',min:54,max:57,w:4},{id:'typenull',min:54,max:58,w:1}],
			night: [{id:'rattata',min:50,max:52,w:30},{id:'rattata',min:50,max:52,w:30},{id:'raticate',min:50,max:52,w:20},{id:'sandile',min:51,max:54,w:10},{id:'toedscool',min:52,max:55,w:5},{id:'stonjourner',min:54,max:57,w:4},{id:'kleavor',min:54,max:58,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_4': {
		land: {
			morning: [{id:'spearow',min:53,max:55,w:30},{id:'rattata',min:53,max:55,w:30},{id:'ekans',min:53,max:55,w:20},{id:'tirtouga',min:56,max:59,w:10},{id:'mamoswine',min:58,max:61,w:5},{id:'lillipup',min:57,max:61,w:4},{id:'sandshrew',min:53,max:55,w:1}],
			day: [{id:'spearow',min:53,max:55,w:30},{id:'rattata',min:53,max:55,w:30},{id:'ekans',min:53,max:55,w:20},{id:'pyukumuku',min:56,max:59,w:10},{id:'basculegion',min:58,max:61,w:5},{id:'skwovet',min:57,max:61,w:4},{id:'sandshrew',min:53,max:55,w:1}],
			night: [{id:'rattata',min:53,max:55,w:30},{id:'rattata',min:53,max:55,w:30},{id:'raticate',min:53,max:55,w:20},{id:'basculin',min:57,max:60,w:10},{id:'dondozo',min:58,max:61,w:5},{id:'fletchling',min:57,max:61,w:4},{id:'clefairy',min:53,max:55,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_5': {
		land: {
			morning: [{id:'pidgey',min:65,max:67,w:30},{id:'snubbull',min:65,max:67,w:30},{id:'pidgeotto',min:65,max:67,w:20},{id:'cosmog',min:65,max:68,w:10},{id:'munna',min:66,max:69,w:5},{id:'elgyem',min:68,max:71,w:4},{id:'comfey',min:69,max:72,w:1}],
			day: [{id:'pidgey',min:65,max:67,w:30},{id:'snubbull',min:65,max:67,w:30},{id:'pidgeotto',min:65,max:67,w:20},{id:'flittle',min:65,max:68,w:10},{id:'tinkatink',min:67,max:70,w:5},{id:'spritzee',min:68,max:71,w:4},{id:'sigilyph',min:69,max:72,w:1}],
			night: [{id:'hoothoot',min:65,max:67,w:30},{id:'meowth',min:65,max:67,w:30},{id:'noctowl',min:65,max:67,w:20},{id:'hatenna',min:65,max:68,w:10},{id:'flabebe',min:67,max:70,w:5},{id:'swirlix',min:68,max:71,w:4},{id:'alcremie',min:70,max:73,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_6': {
		land: {
			morning: [{id:'rattata',min:56,max:58,w:30},{id:'snubbull',min:56,max:58,w:30},{id:'magnemite',min:56,max:58,w:20},{id:'rookidee',min:57,max:60,w:10},{id:'pincurchin',min:59,max:62,w:5},{id:'furfrou',min:60,max:64,w:4},{id:'granbull',min:56,max:58,w:1}],
			day: [{id:'rattata',min:56,max:58,w:30},{id:'snubbull',min:56,max:58,w:30},{id:'magnemite',min:56,max:58,w:20},{id:'shinx',min:57,max:60,w:10},{id:'morpeko',min:59,max:62,w:5},{id:'komala',min:60,max:64,w:4},{id:'granbull',min:56,max:58,w:1}],
			night: [{id:'meowth',min:56,max:58,w:30},{id:'drowzee',min:56,max:58,w:30},{id:'magnemite',min:56,max:58,w:20},{id:'yamper',min:57,max:60,w:10},{id:'rotom',min:60,max:63,w:5},{id:'ambipom',min:60,max:64,w:4},{id:'raticate',min:56,max:58,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_7': {
		land: {
			morning: [{id:'rattata',min:59,max:61,w:30},{id:'spearow',min:59,max:61,w:30},{id:'snubbull',min:59,max:61,w:20},{id:'blipbug',min:59,max:62,w:10},{id:'applin',min:60,max:63,w:5},{id:'cutiefly',min:61,max:64,w:4},{id:'turtwig',min:62,max:65,w:1}],
			day: [{id:'rattata',min:59,max:61,w:30},{id:'spearow',min:59,max:61,w:30},{id:'snubbull',min:59,max:61,w:20},{id:'kricketot',min:59,max:62,w:10},{id:'smoliv',min:60,max:63,w:5},{id:'capsakid',min:61,max:64,w:4},{id:'joltik',min:62,max:65,w:1}],
			night: [{id:'meowth',min:59,max:61,w:30},{id:'murkrow',min:59,max:61,w:30},{id:'houndour',min:59,max:61,w:20},{id:'scatterbug',min:59,max:62,w:10},{id:'surskit',min:60,max:63,w:5},{id:'ferroseed',min:61,max:64,w:4},{id:'rowlet',min:63,max:66,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_8': {
		land: {
			morning: [{id:'snubbull',min:65,max:67,w:30},{id:'pidgeotto',min:65,max:67,w:30},{id:'abra',min:65,max:67,w:20},{id:'milcery',min:66,max:69,w:10},{id:'mimejr',min:67,max:70,w:5},{id:'espurr',min:68,max:71,w:4},{id:'calyrex',min:70,max:73,w:1}],
			day: [{id:'snubbull',min:65,max:67,w:30},{id:'pidgeotto',min:65,max:67,w:30},{id:'abra',min:65,max:67,w:20},{id:'gothita',min:66,max:69,w:10},{id:'fidough',min:67,max:70,w:5},{id:'floette',min:69,max:72,w:4},{id:'sylveon',min:70,max:73,w:1}],
			night: [{id:'meowth',min:65,max:67,w:30},{id:'noctowl',min:65,max:67,w:30},{id:'abra',min:65,max:67,w:20},{id:'solosis',min:66,max:69,w:10},{id:'woobat',min:68,max:71,w:5},{id:'indeedee',min:69,max:72,w:4},{id:'kadabra',min:65,max:67,w:1}],
		},
	},
	'MAP_JOHKANTO_ROUTE_9': {
		land: {
			morning: [{id:'rattata',min:53,max:55,w:30},{id:'spearow',min:53,max:55,w:30},{id:'raticate',min:53,max:55,w:20},{id:'arctovish',min:57,max:60,w:10},{id:'pidove',min:57,max:61,w:5},{id:'rufflet',min:57,max:61,w:4},{id:'marowak',min:53,max:55,w:1}],
			day: [{id:'rattata',min:53,max:55,w:30},{id:'spearow',min:53,max:55,w:30},{id:'raticate',min:53,max:55,w:20},{id:'cryogonal',min:58,max:61,w:10},{id:'pikipek',min:57,max:61,w:5},{id:'chatot',min:57,max:61,w:4},{id:'marowak',min:53,max:55,w:1}],
			night: [{id:'rattata',min:53,max:55,w:30},{id:'venonat',min:53,max:55,w:30},{id:'raticate',min:53,max:55,w:20},{id:'mrrime',min:58,max:61,w:10},{id:'wooloo',min:57,max:61,w:5},{id:'squawkabilly',min:57,max:61,w:4},{id:'raticate',min:53,max:55,w:1}],
		},
		water: [{id:'goldeen',min:53,max:55,w:60},{id:'goldeen',min:53,max:55,w:30},{id:'wiglett',min:53,max:56,w:5},{id:'tympole',min:54,max:57,w:4},{id:'cubchoo',min:54,max:57,w:1}],
		fishing: [{id:'magikarp',min:53,max:55,w:70},{id:'magikarp',min:53,max:55,w:30},{id:'magikarp',min:53,max:55,w:35},{id:'goldeen',min:53,max:55,w:35},{id:'goldeen',min:53,max:55,w:20},{id:'quaxly',min:55,max:58,w:40},{id:'finizen',min:55,max:58,w:40},{id:'shellos',min:55,max:58,w:15},{id:'clauncher',min:56,max:59,w:4},{id:'mantyke',min:56,max:59,w:1}],
	},
	'MAP_JOHKANTO_VIRIDIAN_CITY': {
		water: [{id:'poliwag',min:71,max:73,w:60},{id:'poliwag',min:71,max:73,w:30},{id:'annihilape',min:76,max:79,w:5},{id:'urshifu',min:76,max:79,w:4}],
		fishing: [{id:'magikarp',min:71,max:73,w:70},{id:'magikarp',min:71,max:73,w:30},{id:'magikarp',min:71,max:73,w:35},{id:'poliwag',min:71,max:73,w:35},{id:'poliwag',min:71,max:73,w:20},{id:'hawlucha',min:75,max:78,w:40},{id:'sirfetchd',min:75,max:78,w:40},{id:'cursola',min:75,max:78,w:15},{id:'sneasler',min:76,max:79,w:4},{id:'dhelmise',min:76,max:79,w:1}],
	},
};
