// GENERATED by tools/gen_holewarps.mjs from the decomps' setholewarp — do not edit.
// { <map stem>: <the map you fall to> } — see holes.js
export const HOLE_WARPS = {
	"GraniteCave_B1F": "MAP_GRANITE_CAVE_B2F",
	"Hoenn2_GraniteCave_B1F": "MAP_HOENN2_GRANITE_CAVE_B2F",
	"MirageTower_2F": "MAP_MIRAGE_TOWER_1F",
	"Hoenn2_MirageTower_2F": "MAP_HOENN2_MIRAGE_TOWER_1F",
	"MirageTower_3F": "MAP_MIRAGE_TOWER_2F",
	"Hoenn2_MirageTower_3F": "MAP_HOENN2_MIRAGE_TOWER_2F",
	"MtPyre_2F": "MAP_MT_PYRE_1F",
	"Hoenn2_MtPyre_2F": "MAP_HOENN2_MT_PYRE_1F",
	"SkyPillar_2F": "MAP_SKY_PILLAR_1F",
	"Hoenn2_SkyPillar_2F": "MAP_HOENN2_SKY_PILLAR_1F",
	"SkyPillar_4F": "MAP_SKY_PILLAR_3F",
	"Hoenn2_SkyPillar_4F": "MAP_HOENN2_SKY_PILLAR_3F"
};
