// GENERATED by tools/gen_locked_warps.mjs — do not edit.
// { <map name>: ["x,y", ...] }: warp cells a script locks/unlocks; World.isPassable
// honours their live collision (see the generator for why).
export const LOCKED_WARPS = {
	"AbandonedShip_Corridors_B1F": [
		"11,4"
	],
	"AbandonedShip_HiddenFloorCorridors": [
		"3,8",
		"6,8"
	],
	"AncientTomb": [
		"8,20"
	],
	"BrunosRoom": [
		"4,2",
		"5,2"
	],
	"DesertRuins": [
		"8,20"
	],
	"EverGrandeCity_ChampionsRoom": [
		"6,2"
	],
	"FiveIsland_Meadow": [
		"12,21"
	],
	"GoldenrodUnderground": [
		"18,6"
	],
	"Hoenn2_AbandonedShip_Corridors_B1F": [
		"11,4"
	],
	"Hoenn2_AncientTomb": [
		"8,20"
	],
	"Hoenn2_DesertRuins": [
		"8,20"
	],
	"Hoenn2_EverGrandeCity_ChampionsRoom": [
		"6,2"
	],
	"Hoenn2_IslandCave": [
		"8,20"
	],
	"Hoenn2_JaggedPass": [
		"16,18"
	],
	"Hoenn2_MeteorFalls_1F_1R": [
		"4,2"
	],
	"Hoenn2_NewMauville_Entrance": [
		"4,1"
	],
	"Hoenn2_Route103": [
		"45,6"
	],
	"Hoenn2_Route105": [
		"9,20"
	],
	"Hoenn2_Route110_TrickHouseEnd": [
		"10,1"
	],
	"Hoenn2_Route110_TrickHousePuzzle1": [
		"13,1"
	],
	"Hoenn2_Route111": [
		"29,87"
	],
	"Hoenn2_Route114_FossilManiacsTunnel": [
		"6,2"
	],
	"Hoenn2_Route120": [
		"7,55"
	],
	"Hoenn2_SkyPillar_Outside": [
		"14,5"
	],
	"Hoenn2_SootopolisCity": [
		"31,32",
		"9,6",
		"45,6",
		"9,17",
		"44,17",
		"9,26",
		"53,28",
		"8,35",
		"48,25",
		"51,36"
	],
	"IslandCave": [
		"8,20"
	],
	"JaggedPass": [
		"16,18"
	],
	"KarensRoom": [
		"4,2",
		"5,2"
	],
	"KogasRoom": [
		"4,2",
		"5,2"
	],
	"LancesRoom": [
		"4,23",
		"5,23",
		"4,1",
		"5,1"
	],
	"MeteorFalls_1F_1R": [
		"4,2"
	],
	"MtEmber_Exterior": [
		"42,39"
	],
	"NewMauville_Entrance": [
		"4,1"
	],
	"Route103": [
		"45,6"
	],
	"Route105": [
		"9,20"
	],
	"Route110_TrickHouseEnd": [
		"10,1"
	],
	"Route110_TrickHousePuzzle1": [
		"13,1"
	],
	"Route111": [
		"29,87"
	],
	"Route114_FossilManiacsTunnel": [
		"6,2"
	],
	"Route120": [
		"7,55"
	],
	"RuinsOfAlphAerodactylChamber": [
		"4,0"
	],
	"RuinsOfAlphHoOhChamber": [
		"4,0"
	],
	"RuinsOfAlphKabutoChamber": [
		"4,0"
	],
	"RuinsOfAlphOmanyteChamber": [
		"4,0"
	],
	"SealedChamber_OuterRoom": [
		"10,2"
	],
	"SixIsland_RuinValley": [
		"24,24"
	],
	"SkyPillar_Outside": [
		"14,5"
	],
	"SootopolisCity": [
		"31,32",
		"9,6",
		"45,6",
		"9,17",
		"44,17",
		"9,26",
		"53,28",
		"8,35",
		"48,25",
		"51,36"
	],
	"WillsRoom": [
		"4,2",
		"5,2"
	]
};
