// format.js — deck-format rules shared by client and tooling.
//
// CORRESPONDENCE (play-by-mail) FORMAT: countering is banned (owner rule,
// 2026-09-10). The stack's response windows need a present opponent; in
// correspondence the absent player's priority would be ghost-piloted by AI
// heuristics — so counter cards simply don't exist in this format. Enforced in
// three places, all driven by this module:
//   1. server/mp.mjs rejects decks containing banned ids at async-create/accept
//      (list generated by tools/gen-correspondence-bans.mjs -> correspondence-bans.json)
//   2. game.js startAsync pre-checks the invitee's deck with a friendly overlay
//   3. game.js startAsync filters the match's card universe so conjure/discover/
//      random generation can never produce a counter mid-game
//
// "Countering" = spell-countering only: the counterSpell flag / counter config,
// or any nested effect of the counter family. NOT the +1/+1 counter vocabulary
// ('counter-self' is Champion of the Parish's +1/+1; 'counter-doubler' is
// Vorinclex's static; 'add-counters'/'grow' are stat counters).
const COUNTER_EFFECTS = new Set(['counter', 'counter-stack', 'counter-triggering']);

function treeHasCounter(node) {
	if (!node || typeof node !== 'object') return false;
	if (Array.isArray(node)) return node.some(treeHasCounter);
	if (typeof node.type === 'string' && COUNTER_EFFECTS.has(node.type)) return true;
	for (const k of Object.keys(node)) {
		if (k === 'description' || k === 'text' || k === 'name') continue;
		if (treeHasCounter(node[k])) return true;
	}
	return false;
}

// does this card def counter spells (in any of its modes/triggers)?
export function isCounterCard(def) {
	if (!def) return false;
	if (def.counterSpell || def.counter) return true;
	return treeHasCounter([def.effects, def.choices, def.secret, def.trap, def.kicker,
		def.deathrattle, def.ongoing, def.ongoings, def.activated, def.taps, def.tapAbility,
		def.adventure, def.quest, def.abilities, def.overkill, def.combo, def.miracle]);
}

// the deck's banned ids (for a pre-flight legality check; byId may be the full map)
export function correspondenceOffenders(deckIds, byId) {
	const out = [];
	for (const id of deckIds || []) {
		const def = byId[id];
		if (def && isCounterCard(def)) out.push(id);
	}
	return [...new Set(out)];
}

// the correspondence card universe: the full map minus counter cards. `keepIds`
// grandfathers ids referenced by a pre-format match's decks/snapshot so legacy
// games keep working (their draws still need defs).
export function filterCorrespondence(byId, keepIds) {
	const keep = keepIds || new Set();
	const out = {};
	for (const id of Object.keys(byId)) {
		const def = byId[id];
		if (isCounterCard(def) && !keep.has(id)) continue;
		out[id] = def;
	}
	return out;
}
