// gen_metatile_labels.mjs — the METATILE_* names the transpiled scripts use, as ids.
//
// Every one of the 1,098 `setmetatile` ops in overworld/data/scripts names its tile
// symbolically ("METATILE_VermilionGym_Floor"), the way the decomps write them.
// World.setMetatile did `tile & 0x3FF`, and a string ANDed with a number is 0, so
// every scripted tile edit wrote metatile 0 — the engine's "outside the map", never
// walkable. Gym puzzles, scripted doors and walls across 95 maps opened into void
// (playtest 2026-09-25: the Vermilion Gym beams stayed shut after both switches).
//
// The decomps define the names in include/constants/metatile_labels.h. All 288
// names the scripts use are there. Three mean different tiles in FireRed and
// Emerald (General_CalmWater, General_Door, PokemonCenter_CounterBarrier), so those
// are resolved per MAP, from which decomp the map came from.
//
// Writes overworld/metatile_labels.js.   node tools/gen_metatile_labels.mjs
import fs from 'fs';

const R = 'C:/Users/guide/Desktop/Magepunk66/Reference/';
const parse = g => {
	const m = new Map();
	for (const x of fs.readFileSync(`${R}${g}/include/constants/metatile_labels.h`, 'utf8').matchAll(/#define\s+(METATILE_\w+)\s+(0x[0-9A-Fa-f]+|\d+)/g)) m.set(x[1], Number(x[2]));
	return m;
};
const fr = parse('pokefirered'), em = parse('pokeemerald');
const frMaps = new Set(fs.readdirSync(`${R}pokefirered/data/maps`));
const gameOf = map => (/^Hoenn2_/.test(map) ? 'em' : frMaps.has(map) ? 'fr' : 'em');

const used = new Map();   // name -> Set(map)
const D = 'overworld/data/scripts';
for (const f of fs.readdirSync(D).filter(f => f.endsWith('.json'))) {
	let p; try { p = JSON.parse(fs.readFileSync(`${D}/${f}`, 'utf8')); } catch { continue; }
	const map = f.replace(/\.json$/, '');
	for (const v of Object.values(p)) if (Array.isArray(v)) for (const o of v) {
		if (o && o.op === 'setmetatile' && typeof o.tile === 'string') {
			if (!used.has(o.tile)) used.set(o.tile, new Set());
			used.get(o.tile).add(map);
		}
	}
}
const labels = {}, byMap = {}, missing = [];
for (const [name, maps] of [...used].sort((a, b) => a[0].localeCompare(b[0]))) {
	const a = fr.get(name), b = em.get(name);
	if (a == null && b == null) { missing.push(name); continue; }
	if (a != null && b != null && a !== b) {
		for (const m of maps) (byMap[m] ||= {})[name] = gameOf(m) === 'fr' ? a : b;
	} else labels[name] = a ?? b;
}
if (missing.length) { console.error('unresolved:', missing.join(' ')); process.exit(1); }

const out = `// metatile_labels.js — GENERATED by tools/gen_metatile_labels.mjs; do not edit.
//
// The METATILE_* names the transpiled scripts pass to \`setmetatile\`, as the
// decomps' own ids (include/constants/metatile_labels.h). World.setMetatile
// resolves a string tile through this; see the generator for why.
export const METATILE_LABELS = {
${Object.entries(labels).map(([k, v]) => `\t${k}: 0x${v.toString(16).toUpperCase()},`).join('\n')}
};
// names FireRed and Emerald define differently, resolved per map by source game
export const METATILE_LABELS_BY_MAP = ${JSON.stringify(byMap, null, '\t').replace(/"(\w+)":/g, '$1:')};
export function metatileId(tile, mapName) {
	if (typeof tile !== 'string') return tile;
	if (/^(0x[0-9a-f]+|\\d+)$/i.test(tile)) return Number(tile);
	return METATILE_LABELS_BY_MAP[mapName]?.[tile] ?? METATILE_LABELS[tile];
}
`;
fs.writeFileSync('overworld/metatile_labels.js', out);
console.log(`${Object.keys(labels).length} names + ${Object.keys(byMap).length} maps with per-game overrides; ${[...used.values()].reduce((a, s) => a + s.size, 0)} map uses`);
