// gen_divewarps.mjs — the decomp's `setdivewarp`, which the transpile dropped.
//
// pokeemerald gives the rooms that are entered by DIVE their way back in the map
// scripts, not the map connections: ON_RESUME / ON_DIVE_WARP runs
// `setdivewarp MAP, x, y`, and DIVE (down) or surfacing (up) on that map goes
// there. Without them Underwater_SeafloorCavern had no way up into the cave, so
// Team Aqua's hideout climax was unreachable, and the Abandoned Ship's hidden
// floor had no way back out (2026-10-07). divelinks.js builds the dive/emerge
// links from this table.
//
// Underwater_SealedChamber surfaces in two places depending on where you stand
// (getplayerxy + goto_if_ne): that becomes { at: [x, y] } on the chamber's entry.
//   -> overworld/divewarp_data.js   export const DIVE_WARPS = { <stem>: [ { map, x, y, at? } ] }
//
//   node tools/gen_divewarps.mjs
import fs from 'fs';
import path from 'path';

const REF = process.env.MAGEPUNK_REF || path.resolve('..', 'Magepunk66', 'Reference');
const DATA = path.resolve('overworld', 'data');
const OUT = path.resolve('overworld', 'divewarp_data.js');
const ids = new Set(Object.keys(JSON.parse(fs.readFileSync(path.join(DATA, 'map_index.json'), 'utf8'))));
const out = {};
const warn = [];
for (const game of ['pokeemerald', 'pokefirered']) {
	const root = path.join(REF, game, 'data', 'maps');
	for (const dir of fs.readdirSync(root).sort()) {
		const f = path.join(root, dir, 'scripts.inc');
		if (!fs.existsSync(f)) continue;
		const lines = fs.readFileSync(f, 'utf8').split(/\r?\n/).map(l => l.replace(/@.*$/, '').trim());
		const byLabel = {};
		let label = null;
		for (const l of lines) {
			const m = l.match(/^(\w+)::?$/);
			if (m) { label = m[1]; byLabel[label] = []; continue; }
			if (label && l) byLabel[label].push(l);
		}
		const warps = [];
		for (const [lab, cmds] of Object.entries(byLabel)) {
			for (const c of cmds) {
				const m = c.match(/^setdivewarp\s+(MAP_\w+),\s*(\d+),\s*(\d+)/);
				if (m) warps.push({ label: lab, map: m[1], x: +m[2], y: +m[3] });
			}
		}
		if (!warps.length) continue;
		if (warps.length > 1) {
			// getplayerxy VAR_0x8004, VAR_0x8005; goto_if_ne VAR_0x8004, X, A; goto_if_ne VAR_0x8005, Y, A; goto B
			let at = null;
			for (const cmds of Object.values(byLabel)) {
				const i = cmds.findIndex(c => /^getplayerxy/.test(c));
				if (i < 0) continue;
				const gx = cmds[i + 1]?.match(/^goto_if_ne VAR_0x8004, (\d+), (\w+)/), gy = cmds[i + 2]?.match(/^goto_if_ne VAR_0x8005, (\d+), (\w+)/), g = cmds[i + 3]?.match(/^goto (\w+)/);
				if (gx && gy && g && gx[2] === gy[2]) at = { x: +gx[1], y: +gy[1], hit: g[1], miss: gx[2] };
			}
			if (!at) { warn.push(`${dir}: ${warps.length} setdivewarps, no position rule`); continue; }
			for (const w of warps) if (w.label === at.hit) w.at = [at.x, at.y];
			warps.sort((a, b) => (b.at ? 1 : 0) - (a.at ? 1 : 0));   // the positional one first, the default last
		}
		const list = warps.map(({ map, x, y, at }) => ({ map, x, y, ...(at ? { at } : {}) }));
		const bad = list.filter(w => !ids.has(w.map));
		if (bad.length) warn.push(`${dir}: unknown ${bad.map(b => b.map).join(', ')}`);
		out[dir] = list;
		// the HOENN2 copy of the region, where it has the same rooms
		const h2 = list.map(w => ({ ...w, map: w.map.replace(/^MAP_/, 'MAP_HOENN2_') }));
		if (fs.existsSync(path.join(DATA, 'maps', `Hoenn2_${dir}_map.json`)) && h2.every(w => fs.existsSync(path.join(DATA, 'maps', `Hoenn2_${mapStem(w.map.replace('MAP_HOENN2_', 'MAP_'))}_map.json`)))) out['Hoenn2_' + dir] = h2;
	}
}
function mapStem(id) { return JSON.parse(fs.readFileSync(path.join(DATA, 'map_index.json'), 'utf8'))[id] || '?'; }
const body = `// GENERATED by tools/gen_divewarps.mjs from the decomps' setdivewarp — do not edit.\n// { <map stem>: [ { map, x, y, at? } ] } — see divelinks.js\nexport const DIVE_WARPS = ${JSON.stringify(out, null, '\t')};\n`;
fs.writeFileSync(OUT, body);
console.log(`${Object.keys(out).length} maps with a dive warp -> ${path.relative(process.cwd(), OUT)}`);
if (warn.length) console.log('WARN ' + warn.join('; '));
