// gen_crystal_stds.mjs — give Crystal's shared scripts a body again.
//
// 237 objects and signs across Gen-2 Kanto and Johto do nothing when you talk to
// them. Not because their data is missing — because Crystal factors its common
// NPCs through `jumpstd <StdScript>`, a jump into a shared library, and the
// transpiler emits nothing for that op. A label whose entire body is one jumpstd
// therefore transpiles to NOTHING and vanishes from the script file, so
// runScriptLabel finds no label and the NPC is mute.
//
// Every bookshelf, every POKeMON CENTER and MART sign, every trash can, the Game
// Corner coin vendor, the Team Rocket oath posters. 189 labels, 14 shared scripts.
//
// The engine already has exactly this pattern for the OTHER decomp: events.js's
// COMMON_STUBS gives FireRed's `Common_EventScript_*` bodies. This writes the
// Crystal half — a label -> std id map, paired with bodies in events.js.
//
// Text comes from pokecrystal's own data/text/std_text.asm, so the bookshelves say
// what they say in Crystal rather than something invented.
//
//   node tools/gen_crystal_stds.mjs           (report)
//   node tools/gen_crystal_stds.mjs --write   (write overworld/crystal_stds.js)
import fs from 'fs';
import path from 'path';

const WRITE = process.argv.includes('--write');
const CRY = path.resolve('../Magepunk66/Reference/pokecrystal');
const D = path.resolve('overworld/data');
const regions = JSON.parse(fs.readFileSync(path.resolve('overworld/map_regions.json'), 'utf8'));

// ---------- label -> std, from every map ----------
const stdOf = new Map();
for (const f of fs.readdirSync(path.join(CRY, 'maps')).filter(x => x.endsWith('.asm'))) {
	const src = fs.readFileSync(path.join(CRY, 'maps', f), 'utf8');
	for (const m of src.matchAll(/^([A-Za-z0-9_]+):\s*\n\s*jumpstd\s+([A-Za-z0-9_]+)/gm)) stdOf.set(m[1], m[2]);
}

// ---------- std -> text, from std_text.asm ----------
// `text "..."` / `line "..."` / `cont "..."` / `para "..."` until `done`.
const textOf = new Map();
{
	const src = fs.readFileSync(path.join(CRY, 'data/text/std_text.asm'), 'utf8');
	for (const m of src.matchAll(/^([A-Za-z0-9_]+Text):\n((?:\s*(?:text|line|cont|para|next)\s+"[^"]*"\n|\s*done\n)*)/gm)) {
		const lines = [...m[2].matchAll(/(text|line|cont|para|next)\s+"([^"]*)"/g)];
		if (!lines.length) continue;
		let out = '';
		for (const [, kind, s] of lines) {
			const t = s.replace(/#MON/g, 'POKeMON').replace(/#/g, 'POKe');
			out += (out === '' ? '' : (kind === 'para' ? '\n\n' : '\n')) + t;
		}
		textOf.set(m[1], out.trim());
	}
}

// ---------- which stds actually matter here ----------
const used = new Map();     // std -> count of dropped references
const labels = new Map();   // label -> std, only for labels our data actually points at and lacks
for (const rn of ['JOHKANTO', 'JOHTO', 'KANTO', 'HOENN']) {
	for (const m of regions[rn]) {
		const mp = path.join(D, 'maps', `${m.name}_map.json`);
		if (!fs.existsSync(mp)) continue;
		const map = JSON.parse(fs.readFileSync(mp, 'utf8'));
		const sp = path.join(D, 'scripts', `${m.name}.json`);
		const sc = fs.existsSync(sp) ? JSON.parse(fs.readFileSync(sp, 'utf8')) : null;
		for (const o of [...(map.object_events || []), ...(map.bg_events || [])]) {
			const s = o.script || '';
			const std = stdOf.get(s);
			if (!std) continue;
			if (sc && sc[s]) continue;                 // transpiled fine, leave it
			labels.set(s, std);
			used.set(std, (used.get(std) || 0) + 1);
		}
	}
}

console.log(`Crystal labels that are a bare jumpstd: ${stdOf.size}`);
console.log(`std texts parsed from std_text.asm:    ${textOf.size}`);
console.log(`\ndropped labels our maps point at: ${labels.size}  (${[...used.values()].reduce((a, b) => a + b, 0)} objects/signs)`);
for (const [std, n] of [...used].sort((a, b) => b[1] - a[1])) {
	const t = textOf.get(std.replace(/Script$/, 'Text'));
	console.log(`  ${String(n).padStart(4)}  ${std.padEnd(28)} ${t ? JSON.stringify(t.split('\n')[0]).slice(0, 46) : '(behavioural — needs a body in events.js)'}`);
}

if (WRITE) {
	const rows = [...labels].sort().map(([l, s]) => `\t${JSON.stringify(l)}: '${s}',`).join('\n');
	const texts = [...used.keys()]
		.map(s => [s, textOf.get(s.replace(/Script$/, 'Text'))])
		.filter(([, t]) => t)
		.sort()
		.map(([s, t]) => `\t${s}: ${JSON.stringify(t)},`).join('\n');
	fs.writeFileSync('overworld/crystal_stds.js',
`// crystal_stds.js — GENERATED by tools/gen_crystal_stds.mjs. Re-run it rather than
// editing by hand.
//
// Crystal factors its common NPCs through \`jumpstd <StdScript>\` — a jump into a
// shared script library. The transpiler emits nothing for that op, so a label
// whose entire body is one jumpstd transpiled to NOTHING and vanished from the
// script file: ${[...used.values()].reduce((a, b) => a + b, 0)} objects and signs across Gen-2 Kanto and Johto did nothing at
// all when talked to. Every bookshelf, every POKeMON CENTER and MART sign, every
// trash can, the Game Corner coin vendor.
//
// events.js already does exactly this for the OTHER decomp — COMMON_STUBS gives
// FireRed's \`Common_EventScript_*\` a body. This is the Crystal half.
//
// STD_TEXT is lifted from pokecrystal's own data/text/std_text.asm, so a bookshelf
// says what it says in Crystal.

// the label an object points at -> the shared script it jumps to
export const STD_OF = {
${rows}
};

// the shared scripts that are just a line of text
export const STD_TEXT = {
${texts}
};
`);
	console.log('\nwrote overworld/crystal_stds.js');
} else {
	console.log('\n(dry run — pass --write to emit overworld/crystal_stds.js)');
}
