#!/usr/bin/env python3
"""gen_trainer_pairs.py — which trainer NPCs are ONE trainer (double-battle pairs).

FRLG and Emerald flag a trainer beaten by TRAINER_ id, and a double-battle couple
is two object events whose scripts battle the same id (Route 12's GIA & JES are
both `trainerbattle_double TRAINER_YOUNG_COUPLE_GIA_JES`). The port keys defeat
per event script, and data/trainers.json carries no trainer ids, so beating the
couple from one partner left the other a fresh, paying fight.

This reads every trainerbattle in the two decomps, keeps the ids that two or more
object events on one map battle, and writes overworld/trainer_pairs.js:
  TRAINER_GROUP = { eventScript: 'TRAINER_ID', ... }
trainers.js treats every event sharing a group on a map as one trainer.

  python tools/gen_trainer_pairs.py
"""
import collections, glob, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(os.path.dirname(ROOT), 'Magepunk66', 'Reference')
MAPS = os.path.join(ROOT, 'overworld', 'data', 'maps')
OUT = os.path.join(ROOT, 'overworld', 'trainer_pairs.js')
# `trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_X, ...` names the battle TYPE
# first and the trainer second. The facility types (Pyramid, Trainer Hill, the
# SET_TRAINER pair) carry a placeholder id the facility replaces at run time.
NOT_A_TRAINER = re.compile(r'^TRAINER_BATTLE_')
FACILITY = {'TRAINER_BATTLE_PYRAMID', 'TRAINER_BATTLE_HILL', 'TRAINER_BATTLE_SET_TRAINER_A', 'TRAINER_BATTLE_SET_TRAINER_B'}


def label_trainers():
	out = {}
	for game in ('pokefirered', 'pokeemerald'):
		for f in glob.glob(os.path.join(REF, game, 'data', '**', '*.inc'), recursive=True):
			label = None
			for line in open(f, encoding='utf-8', errors='ignore'):
				m = re.match(r'^(\w+)::', line)
				if m: label = m.group(1); continue
				m = re.match(r'\s*trainerbattle\w*\s+(TRAINER_\w+)(?:\s*,\s*(TRAINER_\w+))?', line)
				if not (m and label) or label in out: continue
				if m.group(1) in FACILITY: out[label] = None; continue
				tid = m.group(2) if NOT_A_TRAINER.match(m.group(1)) and m.group(2) else m.group(1)
				out[label] = None if NOT_A_TRAINER.match(tid) else tid
	return out


def main():
	lab = label_trainers()
	group = {}
	for mf in sorted(glob.glob(os.path.join(MAPS, '*_map.json'))):
		mj = json.load(open(mf, encoding='utf-8'))
		by = collections.defaultdict(set)
		for o in mj.get('object_events', []):
			tid = lab.get(o.get('script'))
			if tid: by[tid].add((o['script'], o.get('x'), o.get('y')))
		for tid, objs in by.items():
			if len(objs) > 1:
				for script, _, _ in objs: group[script] = tid
	lines = ['// GENERATED by tools/gen_trainer_pairs.py: do not edit.',
		'// Event scripts that battle the SAME decomp trainer id from different NPCs on',
		'// one map (double-battle couples, twins, Tate & Liza). Beating one beats all.',
		'export const TRAINER_GROUP = {']
	for script in sorted(group): lines.append(f"\t{script}: '{group[script]}',")
	lines.append('};')
	open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
	print(f'{len(group)} scripts in {len(set(group.values()))} shared trainers -> {os.path.relpath(OUT, ROOT)}')


if __name__ == '__main__':
	main()
