// gen_holewarps.mjs — the decomps' `setholewarp`, which the port never read.
//
// pokeemerald's cracked floors (Sky Pillar 2F/4F, Granite Cave B1F, Mirage Tower,
// Mt. Pyre 2F) drop you to the floor below at the same x, y: the map's ON_RESUME
// script runs `setholewarp MAP_X` (and `setstepcallback STEP_CB_CRACKED_FLOOR`),
// and ON_FRAME's CaveHole_CheckFallDownHole runs `warphole` when the step callback
// says the floor gave way. Without them Sky Pillar 3F's middle pocket — reached
// ONLY by falling through 4F's cracked floor — and with it the stairs on to 5F
// and Rayquaza could never be reached (2026-10-07). holes.js runs the mechanic.
//   -> overworld/holewarp_data.js   export const HOLE_WARPS = { <stem>: 'MAP_...' }
//
//   node tools/gen_holewarps.mjs
import fs from 'fs';
import path from 'path';

const REF = process.env.MAGEPUNK_REF || (() => {
	for (let d = path.resolve('.'); ; d = path.dirname(d)) {
		const c = path.join(path.dirname(d), 'Magepunk66', 'Reference');
		if (fs.existsSync(c)) return c;
		if (path.dirname(d) === d) return path.resolve('..', 'Magepunk66', 'Reference');
	}
})();
const DATA = path.resolve('overworld', 'data');
const OUT = path.resolve('overworld', 'holewarp_data.js');
const index = JSON.parse(fs.readFileSync(path.join(DATA, 'map_index.json'), 'utf8'));
const out = {};
const warn = [];
for (const game of ['pokeemerald', 'pokefirered']) {
	const root = path.join(REF, game, 'data', 'maps');
	for (const dir of fs.readdirSync(root).sort()) {
		const f = path.join(root, dir, 'scripts.inc');
		if (!fs.existsSync(f)) continue;
		const m = fs.readFileSync(f, 'utf8').match(/^\s*setholewarp\s+(MAP_\w+)/m);
		if (!m) continue;
		if (!index[m[1]]) { warn.push(`${dir}: unknown ${m[1]}`); continue; }
		out[dir] = m[1];
		// the HOENN2 copy of the region, where it has the same rooms
		const h2 = m[1].replace(/^MAP_/, 'MAP_HOENN2_');
		if (fs.existsSync(path.join(DATA, 'maps', `Hoenn2_${dir}_map.json`)) && index[h2]) out['Hoenn2_' + dir] = h2;
	}
}
const body = `// GENERATED by tools/gen_holewarps.mjs from the decomps' setholewarp — do not edit.\n// { <map stem>: <the map you fall to> } — see holes.js\nexport const HOLE_WARPS = ${JSON.stringify(out, null, '\t')};\n`;
fs.writeFileSync(OUT, body);
console.log(`${Object.keys(out).length} maps with a hole warp -> ${path.relative(process.cwd(), OUT)}`);
if (warn.length) console.log('WARN ' + warn.join('; '));
