// gen_encounter_games.mjs — which encounter maps came from pokecrystal, for the rate math.
//
// The two generations store an encounter "rate" on different scales:
//   Gen 3 (pokeemerald / pokefirered, wild_encounter.c):
//       Random() % 2880 < rate * 16          -> chance per step = rate / 180
//   Crystal (engine/overworld/wildmons.asm, `db N percent` = N * 255 / 100):
//       Random() < rate                      -> chance per step = rate / 100
// encounters.js rolled rate/100 for everything, so Hoenn and FRLG Kanto ran at 1.8x
// the vanilla encounter rate (Route 111: 10% a step instead of 5.6%).
//
// A map is Crystal-sourced if its id is a pokecrystal map constant and NOT also a
// gen-3 map id (the port's Kanto is FRLG; Crystal's Kanto was renamed
// MAP_JOHKANTO_*, which counts as Crystal). Ten ids exist in both games (Pallet
// Town, Rock Tunnel...): their encounter data is FRLG's (Rock Tunnel 1F rate 7 =
// FRLG, Crystal says 6 percent), so they stay gen 3.
//
// Writes overworld/encounter_games.js. The decomp sources aren't shipped with the
// game, so the list is baked in.
//
//   node tools/gen_encounter_games.mjs
import fs from 'fs';

const R = 'C:/Users/guide/Desktop/Magepunk66/Reference/';
const crystal = new Set([...fs.readFileSync(R + 'pokecrystal/constants/map_constants.asm', 'utf8')
	.matchAll(/^\s*map_const\s+(\w+)/gm)].map(m => 'MAP_' + m[1]));
const gen3 = new Set();
for (const g of ['pokeemerald', 'pokefirered']) {
	for (const d of fs.readdirSync(R + g + '/data/maps')) {
		try { gen3.add(JSON.parse(fs.readFileSync(`${R}${g}/data/maps/${d}/map.json`, 'utf8')).id); } catch { /* not a map dir */ }
	}
}
const enc = JSON.parse(fs.readFileSync('overworld/data/encounters.json', 'utf8'));
const out = Object.keys(enc).filter(id => /^MAP_JOHKANTO_/.test(id) || (crystal.has(id) && !gen3.has(id))).sort();

const body = `// encounter_games.js — GENERATED by tools/gen_encounter_games.mjs; do not edit.
//
// Encounter maps whose wild data came from pokecrystal. Their "rate" is a true
// percent (roll rate/100); every other map's rate is gen 3's (roll rate/180).
// See the generator for the decomp formulas.
export const CRYSTAL_RATE_MAPS = new Set([
${out.map(id => `\t'${id}',`).join('\n')}
]);
`;
fs.writeFileSync('overworld/encounter_games.js', body);
console.log(`${out.length} Crystal-rate maps of ${Object.keys(enc).length} encounter maps`);
