// gen_locked_warps.mjs — the warp cells a script locks or unlocks.
//
// World.isPassable used to let the player onto ANY warp cell ("doors are always
// enterable"): the decomps put most door warps on wall-collision cells (FRLG/
// Emerald enter a door by walking into it), so the port had to. But a door a
// SCRIPT locks then stayed walkable: Goldenrod Underground's Basement Key door
// (Crystal changeblocks a wall over it until you use the key), the Abandoned
// Ship's Storage Key doors, the sealed Regi tombs, Sootopolis's houses during the
// weather crisis, the Elite Four exits — all of them could be walked straight
// through (2026-10-07).
//
// This lists every warp cell that some script edits (a Crystal `changeblock`, a
// FRLG/Emerald `setmetatile`) into a state that is NOT enterable — a wall cell
// whose behavior is not a door/warp — so the engine honours the cell's live
// collision there: open when clear or a door behavior, shut otherwise. Every
// other warp keeps the old always-enterable rule.
//   -> overworld/locked_warps_data.js { <map name>: ["x,y", ...] }
//
//   node tools/gen_locked_warps.mjs
import fs from 'node:fs';
import { loadMap, behaviorAt } from './audit_tile_reach.mjs';
import { metatileId } from '../overworld/metatile_labels.js';

// FRLG/Emerald door + warp behaviors (MB_NON_ANIMATED_DOOR/CAVE_DOOR 0x60 ...
// MB_DEEP_SOUTH_WARP/DOWN_RIGHT_STAIR_WARP 0x6E, MB_ANIMATED_DOOR/WARP_DOOR 0x69)
export const isDoorBehavior = b => b >= 0x60 && b <= 0x6e;
const COLLISION_MASK = 0x0C00;
const flat = o => Array.isArray(o) ? o.flatMap(flat) : (o && typeof o === 'object' ? (o.op ? [o] : Object.values(o).flatMap(flat)) : []);
const readJSON = f => { try { return JSON.parse(fs.readFileSync(f, 'utf8')); } catch (e) { return null; } };

const scripts = {};   // map stem -> ops
const add = (stem, ops) => { (scripts[stem] = scripts[stem] || []).push(...ops); };
for (const f of fs.readdirSync('overworld/data/scripts')) add(f.replace(/\.json$/, ''), flat(readJSON('overworld/data/scripts/' + f)));
for (const f of ['multichoice_data', 'crystal_scriptvar_data', 'missing_labels_data', 'subvar_fix_data', 'fallthrough_data']) {
	for (const [stem, labels] of Object.entries(readJSON(`overworld/${f}.json`)?.patches || {})) add(stem, flat(labels));
}
for (const [stem, v] of Object.entries(readJSON('overworld/crystal_callbacks.json')?.callbacks || {})) add(stem, flat(v));

const out = {};
let governed = 0;
for (const [stem, ops] of Object.entries(scripts).sort()) {
	const id = readJSON(`overworld/data/maps/${stem}_map.json`)?.id;
	const m = id && loadMap(id);
	if (!m) continue;
	for (const w of m.warps) {
		const values = [];
		for (const o of ops) {
			if (o.op === 'setmetatile' && +o.x === w.x && +o.y === w.y) {
				const t = metatileId(o.tile, stem);
				if (t != null) values.push((t & 0x3FF) | (/^(TRUE|1)$/i.test(String(o.impassable)) ? COLLISION_MASK : 0));
			}
			if (o.op === 'changeblock') (o.cells || []).forEach((v, q) => { if (v != null && o.x + (q & 1) === w.x && o.y + (q >> 1) === w.y) values.push(v); });
		}
		if (!values.length) continue;
		// shut = a wall cell that isn't a door/warp (read with the cell swapped in)
		const shut = v => {
			if ((v & COLLISION_MASK) === 0) return false;
			const save = m.layout.map[w.y][w.x];
			m.layout.map[w.y][w.x] = v;
			const b = behaviorAt(m, w.x, w.y);
			m.layout.map[w.y][w.x] = save;
			return !isDoorBehavior(b);
		};
		if (![m.layout.map[w.y][w.x], ...values].some(shut)) continue;
		(out[stem] = out[stem] || []).push(`${w.x},${w.y}`);
		governed++;
	}
}
fs.writeFileSync('overworld/locked_warps_data.js',
	'// GENERATED by tools/gen_locked_warps.mjs — do not edit.\n'
	+ '// { <map name>: ["x,y", ...] }: warp cells a script locks/unlocks; World.isPassable\n'
	+ '// honours their live collision (see the generator for why).\n'
	+ 'export const LOCKED_WARPS = ' + JSON.stringify(out, null, '\t') + ';\n');
console.log(`${governed} lockable warp cells on ${Object.keys(out).length} maps`);
