// gen_crystal_init_events.mjs — the events a Crystal save starts with SET.
//
// pokecrystal's object_events carry an event flag, and CheckObjectFlag
// (engine/overworld/map_objects_2.asm) masks the object when that flag is SET:
//
//     ld b, CHECK_FLAG
//     call EventFlagAction
//     ld a, c
//     and a
//     jr nz, .masked        ; flag set -> hidden
//
// This port instead hid an object whenever it had a flag AT ALL, whatever the
// flag's state (npcs.js: `if (ev.flag && ev.flag !== '0') return;`). So every
// story NPC in the Crystal regions was deleted from the game permanently —
// including MISTY and BLUE, which made two Gen-2 Kanto badges unobtainable and
// left RED unreachable behind an 8-badge gate that could only ever reach 6.
//
// Reading the flag properly is only half of it: a fresh Crystal save is not
// all-clear. `InitializeEventsScript` (engine/events/std_scripts.asm) sets ~95
// events on a new game, and that is what keeps Misty at the Cerulean Cape rather
// than standing in her gym on day one, Blue off the Viridian floor until you
// meet him at Cinnabar, and Ho-Oh off the Tin Tower roof. Without seeding it,
// correct semantics would reveal the whole cast at once.
//
// So this extracts that list verbatim. `variablesprite` and `setflag ENGINE_*`
// lines in the same script are deliberately ignored — sprite swaps and radio
// channels, not object visibility.
//
//   node tools/gen_crystal_init_events.mjs           (report)
//   node tools/gen_crystal_init_events.mjs --write   (write overworld/crystal_init_events.js)
import fs from 'fs';
import path from 'path';

const WRITE = process.argv.includes('--write');
const SRC = path.resolve('../Magepunk66/Reference/pokecrystal/engine/events/std_scripts.asm');
const D = path.resolve('overworld/data');

if (!fs.existsSync(SRC)) { console.error('missing pokecrystal checkout: ' + SRC); process.exit(1); }

const src = fs.readFileSync(SRC, 'utf8');
const m = /^InitializeEventsScript:\n([\s\S]*?)^\s*endcallback/m.exec(src);
if (!m) { console.error('could not find InitializeEventsScript'); process.exit(1); }

const events = [];
for (const line of m[1].split('\n')) {
	const e = /^\s*setevent\s+([A-Z0-9_]+)/.exec(line);
	if (e && !events.includes(e[1])) events.push(e[1]);
}
console.log(`InitializeEventsScript sets ${events.length} distinct events on a new game`);

// which of them are actually an object's gating flag in our data, and where?
const usedBy = new Map();
for (const f of fs.readdirSync(path.join(D, 'maps'))) {
	if (!f.endsWith('_map.json')) continue;
	const j = JSON.parse(fs.readFileSync(path.join(D, 'maps', f), 'utf8'));
	if (!j._crystal_tileset) continue;
	for (const o of j.object_events || []) {
		if (!o.flag || o.flag === '0') continue;
		if (!usedBy.has(o.flag)) usedBy.set(o.flag, []);
		usedBy.get(o.flag).push(f.replace('_map.json', ''));
	}
}
const hit = events.filter(e => usedBy.has(e));
console.log(`of those, gate a real object in our Crystal maps: ${hit.length}`);

// the flags our Crystal objects use that are NOT initialised -> visible from the start
const uninit = [...usedBy.keys()].filter(f => !events.includes(f)).sort();
console.log(`\nCrystal object flags NOT in the init list (so: visible on a fresh save): ${uninit.length}`);
for (const f of uninit.slice(0, 30)) console.log(`  ${f.padEnd(50)} ${[...new Set(usedBy.get(f))].slice(0, 3).join(', ')}`);

// sanity: the ones the Gen-2 Kanto story hangs on
console.log('\n--- the Gen-2 Kanto cast ---');
for (const f of ['EVENT_TRAINERS_IN_CERULEAN_GYM', 'EVENT_VIRIDIAN_GYM_BLUE', 'EVENT_BLUE_IN_CINNABAR',
	'EVENT_CERULEAN_GYM_ROCKET', 'EVENT_ROUTE_25_MISTY_BOYFRIEND', 'EVENT_ROUTE_24_ROCKET',
	'EVENT_VERMILION_CITY_SNORLAX', 'EVENT_RED_IN_MT_SILVER']) {
	console.log(`  ${f.padEnd(38)} ${events.includes(f) ? 'SET at new game -> hidden' : 'clear -> VISIBLE at new game'}`);
}

if (WRITE) {
	fs.writeFileSync(path.resolve('overworld/crystal_init_events.js'),
`// crystal_init_events.js — GENERATED by tools/gen_crystal_init_events.mjs.
// Re-run it rather than editing by hand.
//
// The ${events.length} events pokecrystal's InitializeEventsScript sets on a new game.
//
// Crystal hides an object_event while its flag is SET (CheckObjectFlag masks on
// a set flag; -1 means "always appear"). This port used to hide an object that
// had a flag AT ALL, whichever way the flag pointed — so every story NPC in the
// Crystal regions was gone for good, MISTY and BLUE among them, which made two
// Gen-2 Kanto badges unobtainable and put RED behind a gate that could not open.
//
// Reading the flag correctly needs the right STARTING state too: a fresh Crystal
// save is not all-clear. This list is what keeps Misty at the Cerulean Cape
// instead of in her gym on day one, Blue off the Viridian Gym floor until you
// meet him at Cinnabar, and Ho-Oh off the Tin Tower roof.

export const INIT_EVENTS = [
${events.map(e => `\t'${e}',`).join('\n')}
];
`);
	console.log('\nwrote overworld/crystal_init_events.js');
} else {
	console.log('\n(dry run — pass --write)');
}
