// gen_crystal_trainer_headers.mjs — which Crystal script labels are TRAINER HEADERS.
//
// In pokecrystal a trainer object points at a `trainer` header:
//     TrainerBeautyOlivia:
//         trainer BEAUTY, OLIVIA, EVENT_BEAT_BEAUTY_OLIVIA, BeautyOliviaSeenText, BeautyOliviaBeatenText, 0, .Script
// The engine's trainer machinery runs the header: seen text -> battle ->
// beaten text -> set the beat event. Only a later talk runs `.Script`, the
// after-battle continuation. The transpile dropped the header and kept the
// continuation under the header's label, so a loaded script for
// TrainerBeautyOlivia is her POST-battle line, not her battle (Route 38,
// 2026-09-30). Other labels (TrainerCooltrainermKevin, the Gym Leaders) are
// ordinary scripts that run their own battle.
//
// This emits overworld/crystal_trainers.js: label -> { beat, seen, beaten }.
//
//   node tools/gen_crystal_trainer_headers.mjs [path/to/pokecrystal]
import fs from 'fs';
import path from 'path';

const SRC = process.argv[2] || path.resolve('..', 'Magepunk66', 'Reference', 'pokecrystal');
const mapsDir = path.join(SRC, 'maps');
if (!fs.existsSync(mapsDir)) { console.error('no pokecrystal maps at', mapsDir); process.exit(1); }

const headers = {};
const dupes = [];
for (const f of fs.readdirSync(mapsDir).filter(f => f.endsWith('.asm')).sort()) {
	const lines = fs.readFileSync(path.join(mapsDir, f), 'utf8').split(/\r?\n/);
	let label = null;
	for (const raw of lines) {
		const line = raw.replace(/;.*$/, '').trimEnd();
		const lab = line.match(/^([A-Za-z_][A-Za-z0-9_]*):/);
		if (lab) { label = lab[1]; continue; }
		if (!line.trim()) continue;
		const m = line.match(/^\s+trainer\s+(\w+),\s*(\w+),\s*(\w+),\s*(\w+),\s*(\w+),/);
		if (m && label) {
			const h = { beat: m[3], seen: m[4], beaten: m[5] };
			if (headers[label] && JSON.stringify(headers[label]) !== JSON.stringify(h)) dupes.push(label);
			headers[label] = h;
		}
		label = null;   // the header is the FIRST thing under its label
	}
}
if (dupes.length) { console.error('conflicting headers for', dupes); process.exit(1); }

const out = `// GENERATED by tools/gen_crystal_trainer_headers.mjs from pokecrystal maps/*.asm.
// Crystal script labels that are TRAINER HEADERS (seen text -> battle -> beaten
// text -> beat event). A loaded script under one of these labels is the
// after-battle CONTINUATION (the header's .Script), never the first battle.
// label -> { beat: EVENT_BEAT_*, seen: <SeenText label>, beaten: <BeatenText label> }
export const CRYSTAL_TRAINER_HEADERS = ${JSON.stringify(headers, null, '\t')};

// the header for a trainer event on the CURRENT map, or null. Crystal maps only:
// the Kanto/Hoenn decomp scripts put the battle in the label itself.
export function crystalTrainerHeader(world, script) {
	if (!script || !world || !world.current || !world.current.map || !world.current.map._crystal_tileset) return null;
	return CRYSTAL_TRAINER_HEADERS[script] || null;
}
`;
fs.writeFileSync(path.resolve('overworld', 'crystal_trainers.js'), out);
console.log(`${Object.keys(headers).length} trainer headers -> overworld/crystal_trainers.js`);
